/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ve.edu.ucab.lab.Vista;

import ve.edu.ucab.lab.Controladores.*;
import ve.edu.ucab.lab.modelo.Administrador;
import ve.edu.ucab.lab.modelo.TransaccionesAdministradores;

import javax.swing.*;
import java.awt.*;
import java.time.LocalDate;
import java.util.Random;

/**
 * VentanaAggUsuario es la clase que representa la ventana de agregar usuario en la aplicación.
 * Permite al administrador crear nuevos usuarios con la información proporcionada, así como actualizar
 * o eliminar usuarios.
 *
 * @author Camila Best
 * @author Daniel Agudelo
 * @version 2.25.2
 */

public class VentanaAggUsuario extends javax.swing.JFrame {
    /**
     * Ventana principal de opciones del administrador.
     */
    private VentanaOpcionesAdmi ventanaOpcionesAdmi;
    /**
     * Objeto que representa al administrador que realiza las acciones en esta ventana.
     */
    private Administrador administrador;
    /**
     * Fecha en que se realiza la acción (agregar, actualizar o eliminar un usuario).
     * Se registra automáticamente al realizar una operación.
     */
    private LocalDate fecha;
    /**
     * Tipo de movimiento realizado en la ventana (por ejemplo, "Agregar Usuario").
     * Sirve para registrar la acción ejecutada por el administrador.
     */
    private String movimiento;

    private String rutaImagenes;

    private ControladorCreadorDeRutasDeEjecutable rutasDeEjecutable;

    /**
     * Establece la ventana principal de opciones del administrador.
     *
     * @param ventanaOpcionesAdmi Instancia de la ventana principal del administrador.
     */
    public void setVentanaOpcionesAdmi(VentanaOpcionesAdmi ventanaOpcionesAdmi) {
        this.ventanaOpcionesAdmi = ventanaOpcionesAdmi;
    }


    /**
     * Constructor por defecto. Inicializa la ventana y sus componentes.
     */
    public VentanaAggUsuario(Administrador administrador) {
        initComponents();
        setLocationRelativeTo(null);
        this.administrador=administrador;
        this.fecha = LocalDate.now();
        this.movimiento = "Agregar Usuario";
    }

    public void archivito(String rutaimg,String png){
        rutasDeEjecutable=new ControladorCreadorDeRutasDeEjecutable("",rutaimg,"",png);
        rutasDeEjecutable.rutas();
        rutaImagenes=rutasDeEjecutable.getRutaImagenes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        TituloRapidoCash = new javax.swing.JLabel();
        IconoDinero = new javax.swing.JLabel();
        textCrearUsuario = new javax.swing.JLabel();
        TextNumeroDeTelefonoUsua = new javax.swing.JLabel();
        datoNombre = new javax.swing.JTextField();
        textoIngreseSuCorreo = new javax.swing.JLabel();
        datoCorreoUsua = new javax.swing.JTextField();
        textoCrearPin = new javax.swing.JLabel();
        datoPin = new javax.swing.JPasswordField();
        textNombre = new javax.swing.JLabel();
        datoCedula = new javax.swing.JTextField();
        datoNumeroDeTelefUsua2 = new javax.swing.JTextField();
        textApellido = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        textoCedula = new javax.swing.JLabel();
        datoApellido1 = new javax.swing.JTextField();
        botonVolver = new javax.swing.JButton();
        textoTipoDeCuenta = new javax.swing.JLabel();
        botonCrearUsuario1 = new javax.swing.JButton();
        opcionCuentaCorriente = new JCheckBox();
        opcionCuentaAhorro = new JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RápidoCash");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo.setBackground(new java.awt.Color(204, 204, 255));

        TituloRapidoCash.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        TituloRapidoCash.setText("RápidoCash");

        archivito("src/main/java/Imagenes/Dinero.png","Dinero.png");
        IconoDinero.setIcon(new javax.swing.ImageIcon(rutaImagenes)); // NOI18N

        textCrearUsuario.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        textCrearUsuario.setText("Crear Usuario");

        TextNumeroDeTelefonoUsua.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        TextNumeroDeTelefonoUsua.setText("NÚMERO DE TELÉFONO DEL USUARIO");

        datoNombre.setBackground(new java.awt.Color(204, 204, 255));
        datoNombre.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        datoNombre.setBorder(null);
        datoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datoNombreActionPerformed(evt);
            }
        });

        textoIngreseSuCorreo.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        textoIngreseSuCorreo.setText("CORREO ELECTRÓNICO DEL USUARIO");

        datoCorreoUsua.setBackground(new java.awt.Color(204, 204, 255));
        datoCorreoUsua.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        datoCorreoUsua.setBorder(null);
        datoCorreoUsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datoCorreoUsuaActionPerformed(evt);
            }
        });

        textoCrearPin.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        textoCrearPin.setText("INGRESE UN PIN");

        datoPin.setBackground(new java.awt.Color(204, 204, 255));
        datoPin.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        datoPin.setBorder(null);
        datoPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datoPinActionPerformed(evt);
            }
        });

        textNombre.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        textNombre.setText("NOMBRE DEL USUARIO");

        datoCedula.setBackground(new java.awt.Color(204, 204, 255));
        datoCedula.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        datoCedula.setBorder(null);
        datoCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datoCedulaActionPerformed(evt);
            }
        });

        datoNumeroDeTelefUsua2.setBackground(new java.awt.Color(204, 204, 255));
        datoNumeroDeTelefUsua2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        datoNumeroDeTelefUsua2.setBorder(null);
        datoNumeroDeTelefUsua2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datoNumeroDeTelefUsua2ActionPerformed(evt);
            }
        });

        textApellido.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        textApellido.setText("PRIMER APELLIDO DEL USUARIO");

        separador.setBackground(new java.awt.Color(0, 0, 0));
        separador.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));

        textoCedula.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        textoCedula.setText("CEDÚLA DEL USUARIO");

        datoApellido1.setBackground(new java.awt.Color(204, 204, 255));
        datoApellido1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        datoApellido1.setBorder(null);
        datoApellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datoApellido1ActionPerformed(evt);
            }
        });

        botonVolver.setBackground(new java.awt.Color(204, 204, 204));
        botonVolver.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        textoTipoDeCuenta.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        textoTipoDeCuenta.setText("TIPO DE CUENTA A CREAR");

        botonCrearUsuario1.setBackground(new java.awt.Color(204, 204, 204));
        botonCrearUsuario1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonCrearUsuario1.setText("Crear Usuario");
        botonCrearUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearUsuario1ActionPerformed(evt);
            }
        });

        opcionCuentaCorriente.setText("Cuenta Corriente");
        opcionCuentaCorriente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionCuentaCorrienteActionPerformed(evt);
            }
        });

        opcionCuentaAhorro.setText("Cuenta Ahorro");
        opcionCuentaAhorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionCuentaAhorroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addComponent(TituloRapidoCash)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IconoDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textCrearUsuario))
                        .addContainerGap())
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TextNumeroDeTelefonoUsua)
                                        .addComponent(datoNumeroDeTelefUsua2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(separador)
                                        .addComponent(jSeparator2)
                                        .addComponent(jSeparator4))
                                    .addComponent(datoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textNombre)))
                            .addComponent(textoCedula)
                            .addComponent(datoCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datoApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(fondoLayout.createSequentialGroup()
                                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textoTipoDeCuenta)
                                            .addComponent(datoPin, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(fondoLayout.createSequentialGroup()
                                                .addComponent(opcionCuentaCorriente)
                                                .addGap(36, 36, 36)
                                                .addComponent(opcionCuentaAhorro)))
                                        .addGap(0, 103, Short.MAX_VALUE))
                                    .addGroup(fondoLayout.createSequentialGroup()
                                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textoCrearPin, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(datoCorreoUsua, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                                            .addComponent(textoIngreseSuCorreo, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(botonCrearUsuario1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonVolver)
                                .addGap(34, 34, 34))))))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(TituloRapidoCash)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(IconoDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textNombre)
                    .addComponent(textoIngreseSuCorreo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(datoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                        .addComponent(datoCorreoUsua, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textApellido)
                    .addComponent(textoCrearPin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datoPin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datoApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botonCrearUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textoTipoDeCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoCedula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(datoCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(opcionCuentaCorriente)
                            .addComponent(opcionCuentaAhorro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextNumeroDeTelefonoUsua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(datoNumeroDeTelefUsua2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(112, 112, 112))
        );

        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void datoCorreoUsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datoCorreoUsuaActionPerformed
    }//GEN-LAST:event_datoCorreoUsuaActionPerformed

    /**
     * Método llamado cuando se pulsa el botón de "Volver".
     *
     * @param evt Evento de acción.
     */
    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        ventanaOpcionesAdmi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonVolverActionPerformed

    /**
     * Este método se ejecuta cuando se realiza una acción en el campo de texto "Nombre".
     * Actualmente no tiene implementación, pero puede ser utilizado en el futuro para validaciones
     * o acciones adicionales al interactuar con el campo de nombre.
     *
     * @param evt El evento de acción generado por la interacción del usuario.
     */
    private void datoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datoNombreActionPerformed
    }//GEN-LAST:event_datoNombreActionPerformed

    /**
     * Este método se ejecuta cuando se realiza una acción en el campo de texto "Primer Apellido".
     * Actualmente no tiene implementación, pero puede ser utilizado en el futuro para validaciones
     * o acciones adicionales al interactuar con el campo del primer apellido.
     *
     * @param evt El evento de acción generado por la interacción del usuario.
     */
    private void datoApellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datoApellido1ActionPerformed
    }//GEN-LAST:event_datoApellido1ActionPerformed

    /**
     * Este método se ejecuta cuando se realiza una acción en el campo de texto "Cédula".
     * Actualmente no tiene implementación, pero puede ser utilizado en el futuro para validaciones
     * o acciones adicionales al interactuar con el campo de cédula.
     *
     * @param evt El evento de acción generado por la interacción del usuario.
     */
    private void datoCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datoCedulaActionPerformed
    }//GEN-LAST:event_datoCedulaActionPerformed

    /**
     * Este método se ejecuta cuando se realiza una acción en el campo de texto "Número de Teléfono".
     * Actualmente no tiene implementación, pero puede ser utilizado en el futuro para validaciones
     * o acciones adicionales al interactuar con el campo de número de teléfono.
     *
     * @param evt El evento de acción generado por la interacción del usuario.
     */
    private void datoNumeroDeTelefUsua2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datoNumeroDeTelefUsua2ActionPerformed
    }//GEN-LAST:event_datoNumeroDeTelefUsua2ActionPerformed

    /**
     * Este método se ejecuta cuando se realiza una acción en el campo de texto "PIN".
     * Actualmente no tiene implementación, pero puede ser utilizado en el futuro para validaciones
     * o acciones adicionales al interactuar con el campo del PIN.
     *
     * @param evt El evento de acción generado por la interacción del usuario.
     */
    private void datoPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datoPinActionPerformed
    }//GEN-LAST:event_datoPinActionPerformed


    /**
     * Este método se ejecuta cuando se pulsa el botón "Crear Usuario". Valida los campos y crea un nuevo usuario.
     *
     * @param evt Evento de acción que se dispara al hacer clic en el botón.
     */

    private void botonCrearUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {
        try {

            new AgregarUsuario().manejarAgregarUsuario(
                    datoNombre,
                    datoApellido1,
                    datoCedula,
                    datoNumeroDeTelefUsua2,
                    datoCorreoUsua,
                    datoPin,
                    opcionCuentaCorriente,
                    opcionCuentaAhorro
            );

            JOptionPane.showMessageDialog(this, "Cliente agregado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            /**
             * Aquí está anexado el código para añadir al registro de administrador
             */
            TransaccionesAdministradores transaccionAdmi=new TransaccionesAdministradores(fecha,administrador.getUserAdministrador(),
                    movimiento,datoNumeroDeTelefUsua2.getText(),"");
            ControladorLlenarRegistroActividarAdministrador movAdministrador=new ControladorLlenarRegistroActividarAdministrador(
                    transaccionAdmi);
            movAdministrador.subirMovimientosAdmis();
            limpiarFormulario();
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error inesperado: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Limpia los campos del formulario de agregar usuario.
     */
    private void limpiarFormulario() {
        datoNombre.setText("");
        datoApellido1.setText("");
        datoCedula.setText("");
        datoNumeroDeTelefUsua2.setText("");
        datoCorreoUsua.setText("");
        datoPin.setText("");
        opcionCuentaAhorro.setSelected(false);
        opcionCuentaCorriente.setSelected(false);
    }




    /**
     * Método llamado cuando se pulsa la opción de "Cuenta Corriente".
     *
     * @param evt Evento de acción.
     */
    private void opcionCuentaCorrienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionCuentaCorrienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcionCuentaCorrienteActionPerformed
    /**
     * Método llamado cuando se pulsa la opción de "Cuenta de Ahorro".
     *
     * @param evt Evento de acción.
     */

    private void opcionCuentaAhorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionCuentaAhorroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcionCuentaAhorroActionPerformed

    /**
     * Método principal para ejecutar la ventana.
     *
     * @param args Los argumentos de línea de comandos.
     */

    public static void main(String args[]) {
        // Set the Nimbus look and feel
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        // If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         //For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         //
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAggUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAggUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAggUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        Administrador administrador=null;
        // Create and display the form
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAggUsuario(administrador).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables

    /**
     * Icono de dinero en la interfaz.
     */
    private javax.swing.JLabel IconoDinero;

    /**
     * Texto que indica el número de teléfono del usuario.
     */
    private javax.swing.JLabel TextNumeroDeTelefonoUsua;

    /**
     * Título "Rápido Cash" en la interfaz.
     */
    private javax.swing.JLabel TituloRapidoCash;

    /**
     * Botón para crear un nuevo usuario.
     */
    private javax.swing.JButton botonCrearUsuario1;

    /**
     * Botón para volver a la ventana de opciones del administrador.
     */
    private javax.swing.JButton botonVolver;

    /**
     * Campo de texto para el primer apellido del usuario.
     */
    private javax.swing.JTextField datoApellido1;

    /**
     * Campo de texto para la cédula del usuario.
     */
    private javax.swing.JTextField datoCedula;

    /**
     * Campo de texto para el correo del usuario.
     */
    private javax.swing.JTextField datoCorreoUsua;

    /**
     * Campo de texto para el nombre del usuario.
     */
    private javax.swing.JTextField datoNombre;

    /**
     * Campo de texto para el número de teléfono del usuario.
     */
    private javax.swing.JTextField datoNumeroDeTelefUsua2;

    /**
     * Campo de texto para el PIN del usuario.
     */
    private javax.swing.JPasswordField datoPin;

    /**
     * Panel de fondo de la ventana.
     */
    private javax.swing.JPanel fondo;

    /**
     * Separador en la interfaz.
     */
    private javax.swing.JSeparator jSeparator2;

    /**
     * Otro separador en la interfaz.
     */
    private javax.swing.JSeparator jSeparator4;

    /**
     * Separador en la interfaz.
     */
    private javax.swing.JSeparator jSeparator5;

    /**
     * Separador en la interfaz.
     */
    private javax.swing.JSeparator jSeparator6;

    /**
     * Separador en la interfaz.
     */
    private javax.swing.JSeparator jSeparator7;

    /**
     * Opción para seleccionar cuenta de ahorro.
     */
    private javax.swing.JRadioButton opcionCuentaAhorro;

    /**
     * Opción para seleccionar cuenta corriente.
     */
    private javax.swing.JCheckBox opcionCuentaCorriente;

    /**
     * Separador adicional en la interfaz.
     */
    private javax.swing.JSeparator separador;

    /**
     * Texto que indica el apellido en el formulario.
     */
    private javax.swing.JLabel textApellido;

    /**
     * Texto que indica la creación de un nuevo usuario.
     */
    private javax.swing.JLabel textCrearUsuario;

    /**
     * Texto que indica el nombre del usuario en el formulario.
     */
    private javax.swing.JLabel textNombre;

    /**
     * Texto que indica la cédula del usuario en el formulario.
     */
    private javax.swing.JLabel textoCedula;

    /**
     * Texto que indica el PIN del usuario en el formulario.
     */
    private javax.swing.JLabel textoCrearPin;

    /**
     * Texto que indica el correo del usuario en el formulario.
     */
    private javax.swing.JLabel textoIngreseSuCorreo;

    /**
     * Texto que indica el tipo de cuenta a seleccionar.
     */
    private javax.swing.JLabel textoTipoDeCuenta;

    // End of variables declaration//GEN-END:variables
}
