/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ve.edu.ucab.lab.Vista;

import ve.edu.ucab.lab.Controladores.ControladorCreadorDeRutasDeEjecutable;
import ve.edu.ucab.lab.Controladores.ControladorLlenarBaseDatosMovimientosBancarios;
import ve.edu.ucab.lab.Controladores.ControladorMostrarSaldoActual;
import ve.edu.ucab.lab.modelo.Cliente;
import ve.edu.ucab.lab.modelo.Transacciones;

import java.time.LocalDate;

/**
 * Clase que representa la ventana de consulta de saldo para un cliente del sistema.
 * Esta ventana permite al cliente visualizar su saldo actual y realizar la operación
 * correspondiente.

 * @author Camila Best
 * @version 2.25.2
 */

public class VentanaSaldo extends javax.swing.JFrame {
    /**
     * Ventana de opciones del usuario que invocó esta ventana.
     */
    private VentanaOpcionesUsua ventanaOpcionesUsua;
    /**
     * Cliente asociado a la operación de consulta de saldo.
     */
    private Cliente cliente;
    /**
     * Controlador encargado de mostrar el saldo actual del cliente.
     */
    private ControladorMostrarSaldoActual tablaSaldoActual;
    /**
     * Descripción de la operación que se registra (consulta de saldo).
     */
    private String movimiento;
    /**
     * Fecha de la operación.
     */
    private LocalDate fecha;

    private String rutaImagenes;

    private ControladorCreadorDeRutasDeEjecutable rutasDeEjecutable;

    /**
     * Establece la ventana de opciones del usuario desde la cual se accede a esta ventana.
     *
     * @param ventanaOpcionesUsua la ventana de opciones del usuario
     */

    public void setVentanaOpcionesUsua(VentanaOpcionesUsua ventanaOpcionesUsua) {
        this.ventanaOpcionesUsua = ventanaOpcionesUsua;
    }

    /**
     * Constructor de la ventana de consulta de saldo.
     * Inicializa los componentes de la ventana, configura su posición y
     * carga los datos del cliente para mostrar el saldo actual.
     *
     * @param cliente el cliente cuya información de saldo será mostrada
     */

    public VentanaSaldo(Cliente cliente) {
        initComponents();
        setLocationRelativeTo(null);
        this.cliente = cliente;
        tablaSaldoActual=new ControladorMostrarSaldoActual(cliente,tablaSaldo);
        tablaSaldoActual.mostrarSaldo();
        movimiento="consulta de saldo";
        fecha = LocalDate.now();
        setVisible(true);
    }

    public void archivito(String rutaimg,String png){
        rutasDeEjecutable=new ControladorCreadorDeRutasDeEjecutable("",rutaimg,"",png);
        rutasDeEjecutable.rutas();
        rutaImagenes=rutasDeEjecutable.getRutaImagenes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoSaldo = new javax.swing.JLabel();
        botonVolver1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaSaldo = new javax.swing.JTable();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RápidoCash");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textoSaldo.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        textoSaldo.setForeground(new java.awt.Color(255, 255, 255));
        textoSaldo.setText("Saldo en cuenta");
        getContentPane().add(textoSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        botonVolver1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonVolver1.setText("Volver");
        botonVolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolver1ActionPerformed(evt);
            }
        });
        getContentPane().add(botonVolver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, 180, 60));

        tablaSaldo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Saldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaSaldo.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tablaSaldoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(tablaSaldo);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 320, 60));

        archivito("src/main/java/Imagenes/Fondo.png","Fondo.png");
        fondo.setIcon(new javax.swing.ImageIcon(rutaImagenes)); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Acción que se ejecuta al hacer clic en el botón "Volver".
     * Registra la consulta en la base de datos de movimientos y vuelve a la ventana
     * de opciones del usuario.
     *
     * @param evt el evento de acción
     */

    private void botonVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolver1ActionPerformed
        // TODO add your handling code here:
        Transacciones deposito = new Transacciones(fecha,movimiento, cliente.getNombreCliente(),
                cliente.getApellidoCliente(), cliente.getTelefonoCliente(),0.0,
                cliente.getCuenta().getTipoCuentaCliente(),"","");
        ControladorLlenarBaseDatosMovimientosBancarios movCliente=new ControladorLlenarBaseDatosMovimientosBancarios(deposito);
        movCliente.subirMovimientos();
        VentanaOpcionesUsua ventana = VentanaOpcionesUsua.getInstance();
        ventana.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_botonVolver1ActionPerformed

    /**
     * Acción que se ejecuta cuando se añade un ancestro a la tabla de saldo.
     *
     * @param evt el evento de ancestro
     */

    private void tablaSaldoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tablaSaldoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaSaldoAncestorAdded

    /**
     * Método principal para ejecutar la ventana de consulta de saldo.
     * Inicializa y muestra la interfaz gráfica.
     *
     * @param args argumentos de la línea de comandos
     */

    public static void main(String args[]) {
        // Set the Nimbus look and feel
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        // If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         // For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         //
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        // Create and display the form
        Cliente cliente=null;
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaSaldo(cliente).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    /**
     * Botón que permite al cliente volver a la ventana anterior.
     */
    private javax.swing.JButton botonVolver1;

    /**
     * Fondo de la ventana.
     */
    private javax.swing.JLabel fondo;

    /**
     * Contenedor de desplazamiento para la tabla de saldo.
     */
    private javax.swing.JScrollPane jScrollPane2;

    /**
     * Tabla que muestra el saldo actual del cliente.
     */
    private javax.swing.JTable tablaSaldo;

    /**
     * Etiqueta que muestra el título "Saldo Actual".
     */
    private javax.swing.JLabel textoSaldo;
    // End of variables declaration//GEN-END:variables
}
