/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ve.edu.ucab.lab.Vista;

import ve.edu.ucab.lab.Controladores.*;
import ve.edu.ucab.lab.modelo.Cliente;
import ve.edu.ucab.lab.modelo.Transacciones;

import java.time.LocalDate;

/**
 * La clase VentanaCambiarPinUsuario representa una ventana que permite a los usuarios cambiar su PIN.
 * Esta ventana está asociada a un cliente específico y permite interactuar con los campos para cambiar el PIN.
 *
 * @author Camila Best
 * @version 2.28.6
 */
public class VentanaCambiarPinUsuario extends javax.swing.JFrame {
    /**
     * Ventana de opciones del usuario a la que se volverá al realizar acciones de cambio de PIN.
     */
    private VentanaOpcionesUsua ventanaOpcionUsuario;
    /**
     * Cliente asociado al cambio de PIN. Este cliente contiene la información del usuario que está cambiando su PIN.
     */
    private Cliente cliente;
    /**
     * Descripción de la operación que se registra (consulta de saldo).
     */
    private String movimiento;
    /**
     * Fecha de la operación.
     */
    private LocalDate fecha;

    /**
     * Establece la ventana principal de opciones del usuario.
     *
     * @param ventanaOpcionUsuario La ventana de opciones del usuario a la que se puede volver desde esta ventana.
     */
    public void setVentanaOpcionUsuario(VentanaOpcionesUsua ventanaOpcionUsuario) {
        this.ventanaOpcionUsuario = ventanaOpcionUsuario;
    }

    /**
     * Constructor que inicializa la ventana y recibe un objeto Cliente.
     * El cliente se utiliza para interactuar con la información del usuario en esta ventana.
     *
     * @param cliente El cliente cuyos datos serán utilizados en la ventana de cambio de PIN.
     */
    public VentanaCambiarPinUsuario(Cliente cliente) {
        initComponents();
        setLocationRelativeTo(null);
        this.cliente = cliente;
        movimiento="Cambiar Pin";
        fecha = LocalDate.now();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoBlanco = new javax.swing.JPanel();
        javax.swing.JButton cambiarPin = new javax.swing.JButton();
        IconoDinero = new javax.swing.JLabel();
        TituloRapidoCash = new javax.swing.JLabel();
        TextCambioDePin = new javax.swing.JLabel();
        TextNumeroDeTelefonoUsua = new javax.swing.JLabel();
        Separardor1 = new javax.swing.JSeparator();
        TextoIngreseSuCorreo = new javax.swing.JLabel();
        datoCorreoUsua = new javax.swing.JTextField();
        Separador2 = new javax.swing.JSeparator();
        TextPinAnterior = new javax.swing.JLabel();
        datoPinAnterior = new javax.swing.JPasswordField();
        Separador3 = new javax.swing.JSeparator();
        TextPinNuevo = new javax.swing.JLabel();
        datoPinNuevo = new javax.swing.JPasswordField();
        Separador4 = new javax.swing.JSeparator();
        volverMenu = new javax.swing.JButton();
        datoNumTelfUsua = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RápidoCash");
        setPreferredSize(new java.awt.Dimension(830, 501));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondoBlanco.setBackground(new java.awt.Color(204, 204, 255));
        fondoBlanco.setPreferredSize(new java.awt.Dimension(830, 504));

        cambiarPin.setBackground(new java.awt.Color(204, 204, 204));
        cambiarPin.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cambiarPin.setText("Cambiar pin");
        cambiarPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarPinActionPerformed(evt);
            }
        });

        TituloRapidoCash.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        TituloRapidoCash.setText("RápidoCash");

        TextCambioDePin.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        TextCambioDePin.setText("CAMBIO DE PIN");

        TextNumeroDeTelefonoUsua.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        TextNumeroDeTelefonoUsua.setText("INGRESE SU NÚMERO DE TELÉFONO");

        Separardor1.setForeground(new java.awt.Color(0, 0, 0));

        TextoIngreseSuCorreo.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        TextoIngreseSuCorreo.setText("INGRESE SU CORREO");

        datoCorreoUsua.setBackground(new java.awt.Color(204, 204, 255));
        datoCorreoUsua.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        datoCorreoUsua.setBorder(null);

        Separador2.setForeground(new java.awt.Color(0, 0, 0));

        TextPinAnterior.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        TextPinAnterior.setText("INGRESE SU PIN ANTERIOR");

        datoPinAnterior.setBackground(new java.awt.Color(204, 204, 255));
        datoPinAnterior.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        datoPinAnterior.setBorder(null);

        Separador3.setForeground(new java.awt.Color(0, 0, 0));

        TextPinNuevo.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        TextPinNuevo.setText("INGRESE SU NUEVO PIN");

        datoPinNuevo.setBackground(new java.awt.Color(204, 204, 255));
        datoPinNuevo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        datoPinNuevo.setBorder(null);

        Separador4.setForeground(new java.awt.Color(0, 0, 0));

        volverMenu.setBackground(new java.awt.Color(204, 204, 204));
        volverMenu.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        volverMenu.setText("Volver");
        volverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverMenuActionPerformed(evt);
            }
        });

        datoNumTelfUsua.setBackground(new java.awt.Color(204, 204, 255));
        datoNumTelfUsua.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        datoNumTelfUsua.setBorder(null);

        javax.swing.GroupLayout fondoBlancoLayout = new javax.swing.GroupLayout(fondoBlanco);
        fondoBlanco.setLayout(fondoBlancoLayout);
        fondoBlancoLayout.setHorizontalGroup(
            fondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoBlancoLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(fondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoBlancoLayout.createSequentialGroup()
                        .addGroup(fondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoBlancoLayout.createSequentialGroup()
                                .addGroup(fondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextCambioDePin)
                                    .addComponent(TituloRapidoCash))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IconoDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Separador3, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datoPinAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextPinAnterior)
                            .addComponent(Separador2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datoCorreoUsua, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoIngreseSuCorreo))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoBlancoLayout.createSequentialGroup()
                        .addGroup(fondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(fondoBlancoLayout.createSequentialGroup()
                                .addComponent(cambiarPin, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(volverMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(fondoBlancoLayout.createSequentialGroup()
                                .addGroup(fondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Separardor1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextNumeroDeTelefonoUsua)
                                    .addComponent(datoNumTelfUsua, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                                .addGroup(fondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextPinNuevo)
                                    .addComponent(datoPinNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Separador4, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(124, 124, 124))))
        );
        fondoBlancoLayout.setVerticalGroup(
            fondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoBlancoLayout.createSequentialGroup()
                .addGroup(fondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoBlancoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(IconoDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fondoBlancoLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(TituloRapidoCash)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextCambioDePin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(fondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(fondoBlancoLayout.createSequentialGroup()
                        .addComponent(TextNumeroDeTelefonoUsua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(datoNumTelfUsua, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Separardor1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fondoBlancoLayout.createSequentialGroup()
                        .addComponent(TextPinNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(datoPinNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Separador4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextoIngreseSuCorreo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datoCorreoUsua, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Separador2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextPinAnterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datoPinAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Separador3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(fondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cambiarPin, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(volverMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        getContentPane().add(fondoBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Este método se ejecuta cuando el usuario presiona el botón "Volver".
     * Vuelve a la ventana principal de opciones del usuario.
     *
     * @param evt Evento generado al hacer clic en el botón.
     */
    private void volverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverMenuActionPerformed
        ventanaOpcionUsuario.setVisible(true);
       this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_volverMenuActionPerformed

    /**
     * Este método se ejecuta cuando el usuario presiona el botón para cambiar el PIN.
     * Aún no tiene lógica implementada para cambiar el PIN, pero se debe agregar la funcionalidad correspondiente.
     *
     * @param evt Evento generado al hacer clic en el botón para cambiar el PIN.
     */

    private void cambiarPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarPinActionPerformed
        // TODO add your handling code here:
        ControladorCorreoCorrecto correo= new ControladorCorreoCorrecto(datoCorreoUsua.getText());
        correo.confirmarCorreo();
        ControladorDatosNumericosCorrectos telefonoCorrecto=new ControladorDatosNumericosCorrectos(datoNumTelfUsua.getText(),
                "11","Telefónico");
        telefonoCorrecto.confirmarDatos();
        String pinNuevoString=new String(datoPinNuevo.getPassword());
        String pinViejoString=new String(datoPinAnterior.getPassword());
        ControladorDatosNumericosCorrectos pinNuevo=new ControladorDatosNumericosCorrectos(pinNuevoString,"4",
                "Nuevo pin");
        pinNuevo.confirmarDatos();
        ControladorDatosNumericosCorrectos pinViejo=new ControladorDatosNumericosCorrectos(pinViejoString,"4",
                "Pin Anterior");
        pinViejo.confirmarDatos();
        if (pinViejo.errorNum() && pinViejo.errorNum() && telefonoCorrecto.errorNum() && correo.correoCorrecto()){
            ControladorCambiarPinCliente cambioPin=new ControladorCambiarPinCliente(datoNumTelfUsua.getText(),
                    datoCorreoUsua.getText(),pinNuevoString,pinViejoString,cliente);
            cambioPin.cambiarPin();
            if (cambioPin.esCorrecto()){
                datoCorreoUsua.setText(cambioPin.getCorreoCliente());
                datoNumTelfUsua.setText(cambioPin.getNumeroTelfCliente());
                datoPinAnterior.setText(cambioPin.getPinViejo());
                datoPinNuevo.setText(cambioPin.getNuevoPin());
                Transacciones pinCambiado=new Transacciones(fecha,movimiento,cliente.getNombreCliente(),
                        cliente.getApellidoCliente(),cliente.getTelefonoCliente(),0.0,
                        cliente.getCuenta().getTipoCuentaCliente(),"","");
                ControladorLlenarBaseDatosMovimientosBancarios movCliente=new
                        ControladorLlenarBaseDatosMovimientosBancarios(pinCambiado);
                movCliente.subirMovimientos();
                ventanaOpcionUsuario.setVisible(true);
                this.setVisible(false);
            }
            else {
                datoCorreoUsua.setText(cambioPin.getCorreoCliente());
                datoNumTelfUsua.setText(cambioPin.getNumeroTelfCliente());
                datoPinAnterior.setText(cambioPin.getPinViejo());
                datoPinNuevo.setText(cambioPin.getNuevoPin());
            }
        }
        if (!pinViejo.errorNum()){
            datoPinAnterior.setText("");
        }
        if (!pinNuevo.errorNum()){
            datoPinNuevo.setText("");

        }
        if(!telefonoCorrecto.errorNum()){
            datoNumTelfUsua.setText("");

        }
        if(!correo.correoCorrecto()){
            datoCorreoUsua.setText("");
        }
    }//GEN-LAST:event_cambiarPinActionPerformed

   /**
     * El método main, que inicializa y muestra la ventana de cambio de PIN para un cliente específico.
     *
     * @param args Argumentos de línea de comandos.
     */

    public static void main(String args[]) {
        // Set the Nimbus look and feel
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        // If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         // For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCambiarPinUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCambiarPinUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCambiarPinUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCambiarPinUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        Cliente cliente=null;

        // Create and display the form
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCambiarPinUsuario(cliente).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    /**
     * Etiqueta que muestra un ícono de dinero en la interfaz.
     */
    private javax.swing.JLabel IconoDinero;

    /**
     * Separador horizontal en la interfaz, utilizado para dividir secciones.
     */
    private javax.swing.JSeparator Separador2;

    /**
     * Otro separador horizontal que divide diferentes áreas en la interfaz.
     */
    private javax.swing.JSeparator Separador3;

    /**
     * Otro separador horizontal en la interfaz para mejorar la organización visual.
     */
    private javax.swing.JSeparator Separador4;

    /**
     * Un separador adicional que se utiliza para mejorar la disposición visual de los elementos en la interfaz.
     */
    private javax.swing.JSeparator Separardor1;

    /**
     * Etiqueta que muestra el texto "Cambio de PIN", indicando la acción que el usuario está realizando.
     */
    private javax.swing.JLabel TextCambioDePin;

    /**
     * Etiqueta que muestra el texto "Número de Teléfono Usuario", solicitando el número de teléfono del usuario.
     */
    private javax.swing.JLabel TextNumeroDeTelefonoUsua;

    /**
     * Etiqueta que indica el campo de entrada para el PIN anterior.
     */
    private javax.swing.JLabel TextPinAnterior;

    /**
     * Etiqueta que indica el campo para ingresar el nuevo PIN.
     */
    private javax.swing.JLabel TextPinNuevo;

    /**
     * Etiqueta que solicita al usuario que ingrese su correo electrónico.
     */
    private javax.swing.JLabel TextoIngreseSuCorreo;

    /**
     * Título principal en la interfaz de usuario, generalmente el nombre de la aplicación o sección.
     */
    private javax.swing.JLabel TituloRapidoCash;

    /**
     * Campo de texto donde el usuario ingresa su correo electrónico para la recuperación de PIN.
     */
    private javax.swing.JTextField datoCorreoUsua;

    /**
     * Campo de texto donde el usuario ingresa su número de teléfono para la recuperación de PIN.
     */
    private javax.swing.JTextField datoNumTelfUsua;

    /**
     * Campo de contraseña donde el usuario ingresa su PIN anterior para validarlo antes de cambiarlo.
     */
    private javax.swing.JPasswordField datoPinAnterior;

    /**
     * Campo de contraseña donde el usuario ingresa el nuevo PIN que desea establecer.
     */
    private javax.swing.JPasswordField datoPinNuevo;

    /**
     * Panel que contiene los componentes visuales de fondo de color blanco.
     */
    private javax.swing.JPanel fondoBlanco;

    /**
     * Botón que permite al usuario regresar al menú anterior.
     */
    private javax.swing.JButton volverMenu;
// End of variables declaration//GEN-END:variables


}
