/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ve.edu.ucab.lab.Vista;

import ve.edu.ucab.lab.Controladores.ControladorCreadorDeRutasDeEjecutable;
import ve.edu.ucab.lab.Controladores.ControladorDatosNumericosCorrectos;
import ve.edu.ucab.lab.Controladores.ControladorEntradaID;
import ve.edu.ucab.lab.Controladores.ControladorLlenarBaseDatosMovimientosBancarios;
import ve.edu.ucab.lab.modelo.Cliente;
import ve.edu.ucab.lab.modelo.Transacciones;

import java.time.LocalDate;

/**
 * Clase que representa la ventana para verificar la identificación del cliente.
 *
 * Este formulario solicita al cliente los últimos dos dígitos de su cédula para validar
 * la operación de retiro rápido. Una vez validado, registra el movimiento y procede
 * con la operación.
 *
 * @author Camila Best
 * @version 2.25.2
 */

public class VentanaVerificarId extends javax.swing.JFrame {
    /**
     * Ventana desde la cual se accedió a esta funcionalidad (retiro rápido).
     */
    private VentanaRetiroRapido ventanaRetiroRapido;
    /**
     * Monto del retiro rápido.
     */
    private double datMonto;
    /**
     * Cliente asociado al retiro.
     */
    private Cliente cliente;
    /**
     * Descripción de la operación (retiro).
     */
    private String movimiento;
    /**
     * Fecha de la operación.
     */
    private LocalDate fecha;

    private String rutaImagenes;

    private ControladorCreadorDeRutasDeEjecutable rutasDeEjecutable;

    /**
     * Establece la ventana de retiro rápido que invocó esta funcionalidad.
     *
     * @param ventanaRetiroRapido la ventana de retiro rápido
     */

    public void setVentanaRetiroRapido(VentanaRetiroRapido ventanaRetiroRapido) {
        this.ventanaRetiroRapido = ventanaRetiroRapido;
    }

    /**
     * Constructor que inicializa la ventana de verificación de identificación.
     *
     * @param datMonto el monto del retiro rápido
     * @param cliente el cliente asociado al retiro
     */
    public VentanaVerificarId(double datMonto, Cliente cliente) {
        initComponents();
        setLocationRelativeTo(null);
        this.datMonto = datMonto;
        this.cliente = cliente;
        movimiento="retiro";
        fecha = LocalDate.now();
    }

    public void archivito(String rutaimg,String png){
        rutasDeEjecutable=new ControladorCreadorDeRutasDeEjecutable("",rutaimg,"",png);
        rutasDeEjecutable.rutas();
        rutaImagenes=rutasDeEjecutable.getRutaImagenes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextoID = new javax.swing.JLabel();
        TextoVerificar = new javax.swing.JLabel();
        datoUltimosDosDigitosId = new javax.swing.JPasswordField();
        BotonSiguiente = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RápidoCash");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextoID.setFont(new java.awt.Font("Roboto Black", 0, 22)); // NOI18N
        TextoID.setForeground(new java.awt.Color(255, 255, 255));
        TextoID.setText("INDIQUE LOS DOS ÚLTIMOS DIGITOS DE");
        getContentPane().add(TextoID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 460, -1));

        TextoVerificar.setFont(new java.awt.Font("Roboto Black", 0, 30)); // NOI18N
        TextoVerificar.setForeground(new java.awt.Color(255, 255, 255));
        TextoVerificar.setText("SU CÉDULA PARA VERIFICAR SU IDENTIDAD");
        getContentPane().add(TextoVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 690, -1));

        datoUltimosDosDigitosId.setBackground(new java.awt.Color(53, 51, 205));
        datoUltimosDosDigitosId.setFont(new java.awt.Font("Roboto Black", 0, 24));
        datoUltimosDosDigitosId.setForeground(new java.awt.Color(255, 255, 255));
        datoUltimosDosDigitosId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        datoUltimosDosDigitosId.setBorder(null);
        datoUltimosDosDigitosId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datoUltimosDosDigitosIdActionPerformed(evt);
            }
        });
        getContentPane().add(datoUltimosDosDigitosId, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 240, 80));

        BotonSiguiente.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        BotonSiguiente.setText("Siguiente");
        BotonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(BotonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 240, 70));

        botonVolver.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        botonVolver.setText("Volver");
        botonVolver.setBorder(null);
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(botonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 240, 70));

        Fondo.setBackground(new java.awt.Color(0, 0, 102));

        archivito("src/main/java/Imagenes/Fondo.png","Fondo.png");
        Fondo.setIcon(new javax.swing.ImageIcon(rutaImagenes)); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Acción que se ejecuta cuando se interactúa con el campo de entrada de los últimos dos dígitos
     * de la cédula del cliente.
     *
     * @param evt el evento de acción generado al interactuar con el campo de entrada.
     */

    private void datoUltimosDosDigitosIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datoUltimosDosDigitosIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datoUltimosDosDigitosIdActionPerformed

    /**
     * Acción que se ejecuta al presionar el botón "Volver".
     * Redirige al usuario a la ventana de retiro rápido.
     *
     * @param evt el evento de acción
     */

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        // TODO add your handling code here:
        ventanaRetiroRapido.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonVolverActionPerformed

    /**
     * Acción que se ejecuta al presionar el botón "Siguiente".
     * Valida los últimos dos dígitos de la cédula del cliente, registra el retiro en la base de datos
     * y redirige a la ventana final en caso de éxito.
     *
     * @param evt el evento de acción
     */

    private void botonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSiguienteActionPerformed
        String cedula = datoUltimosDosDigitosId.getText();
        ControladorDatosNumericosCorrectos ci =new ControladorDatosNumericosCorrectos(cedula,"2","Cédula");
        ci.confirmarDatos();
        if (ci.errorNum()){
            ControladorEntradaID id =new ControladorEntradaID(cliente,cedula);
            id.confirmarCi();
            if (id.cedulaCorrecta()){
                Transacciones retirado = new Transacciones(fecha,movimiento, cliente.getNombreCliente(),
                        cliente.getApellidoCliente(), cliente.getTelefonoCliente(),datMonto,
                        cliente.getCuenta().getTipoCuentaCliente(),"","");
                ControladorLlenarBaseDatosMovimientosBancarios movCliente=new ControladorLlenarBaseDatosMovimientosBancarios(retirado);
                movCliente.subirMovimientos();
                VentanaFinal ventanaFinal = new VentanaFinal(cliente);
                ventanaFinal.setVisible(true);
                this.setVisible(false);
            }
            else {
                datoUltimosDosDigitosId.setText("");
            }
        }
        datoUltimosDosDigitosId.setText("");

    }//GEN-LAST:event_BotonSiguienteActionPerformed

    /**
     * Método principal para ejecutar la ventana de verificación de identificación.
     *
     * @param args argumentos de la línea de comandos
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaVerificarId.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaVerificarId.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaVerificarId.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaVerificarId.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /**
         * Si hay problemas busca aquí
         */
        double datMonto=0.0;
        Cliente cliente=null;
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaVerificarId(datMonto,cliente).setVisible(true);
            }
        });
    }

    // Variables declaration - no modificar
    /**
     * Botón que confirma la operación y avanza al siguiente paso.
     */
    private javax.swing.JButton BotonSiguiente;

    /**
     * Fondo de la ventana.
     */
    private javax.swing.JLabel Fondo;

    /**
     * Etiqueta para mostrar "Verificar Identificación".
     */
    private javax.swing.JLabel TextoVerificar;

    /**
     * Etiqueta para instruir al cliente que ingrese los últimos dos dígitos de su ID.
     */
    private javax.swing.JLabel TextoID;

    /**
     * Campo de entrada para los últimos dos dígitos de la cédula del cliente.
     */
    private javax.swing.JPasswordField datoUltimosDosDigitosId;

    /**
     * Botón que permite regresar a la ventana de retiro rápido.
     */
    private javax.swing.JButton botonVolver;
    // End of variables declaration
}
