/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ve.edu.ucab.lab.Vista;

import ve.edu.ucab.lab.Controladores.ControladorCreadorDeRutasDeEjecutable;
import ve.edu.ucab.lab.modelo.Administrador;

import java.time.LocalDate;

/**
 * Falta Descripción.
 *
 * @author Camila Best
 * @version 2.12.1
 */

public class VentanaOpcionesAdmi extends javax.swing.JFrame {
    /**
     * Referencia a la ventana principal del administrador.
     */
        private VentanaAdmin ventanaAdmin;
    /**
     * Objeto que representa al administrador actual.
     */
        private Administrador administrador;

        private String rutaImagenes;

        private ControladorCreadorDeRutasDeEjecutable rutasDeEjecutable;
    /**
     * Establece la ventana principal del administrador.
     *
     * @param ventanaAdmin La instancia de la ventana principal del administrador.
     */

    public void setVentanaAdmin(VentanaAdmin ventanaAdmin) {
        this.ventanaAdmin = ventanaAdmin;
    }

    /**
     * Creates new form VentanaOpcionesAdmi
     */
    public VentanaOpcionesAdmi(Administrador administrador) {
        initComponents();
        setLocationRelativeTo(null);
        this.administrador = administrador;
        System.out.println(administrador.getNombreAdministrador());

    }

    public void archivito(String rutaimg,String png){
        rutasDeEjecutable=new ControladorCreadorDeRutasDeEjecutable("",rutaimg,"",png);
        rutasDeEjecutable.rutas();
        rutaImagenes=rutasDeEjecutable.getRutaImagenes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoMovimientos = new javax.swing.JLabel();
        botonAggUsuario1 = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        botonEliminarUsuario = new javax.swing.JButton();
        registroAdministrador = new javax.swing.JButton();
        botonActualizarUsuario2 = new javax.swing.JButton();
        botonRegistroUsuario = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RápidoCash");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textoMovimientos.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        textoMovimientos.setForeground(new java.awt.Color(255, 255, 255));
        textoMovimientos.setText("Elija la operación a realizar como Administrador ");
        getContentPane().add(textoMovimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        botonAggUsuario1.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        botonAggUsuario1.setText("Agregar usuario");
        botonAggUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAggUsuario1ActionPerformed(evt);
            }
        });
        getContentPane().add(botonAggUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 290, 70));

        botonSalir.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, 290, 70));

        botonEliminarUsuario.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        botonEliminarUsuario.setText("Eliminar Usuario");
        botonEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(botonEliminarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 290, 70));

        registroAdministrador.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        registroAdministrador.setText("Registro Administrador");
        registroAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroAdministradorActionPerformed(evt);
            }
        });
        getContentPane().add(registroAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 290, 70));

        botonActualizarUsuario2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        botonActualizarUsuario2.setText("Actualizar usuario");
        botonActualizarUsuario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarUsuario2ActionPerformed(evt);
            }
        });
        getContentPane().add(botonActualizarUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 290, 70));

        botonRegistroUsuario.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        botonRegistroUsuario.setText("Registro Usuario");
        botonRegistroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistroUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegistroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 290, 70));

        archivito("src/main/java/Imagenes/Fondo.png","Fondo.png");
        fondo.setIcon(new javax.swing.ImageIcon(rutaImagenes)); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarUsuarioActionPerformed
        // TODO add your handling code here:
        VentanaEliminarUsuario ventanaEliminarUsuario = new VentanaEliminarUsuario(administrador);
        ventanaEliminarUsuario.setVentanaOpcionesAdmi(this);
        ventanaEliminarUsuario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonEliminarUsuarioActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        ventanaAdmin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonAggUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAggUsuario1ActionPerformed
        // TODO add your handling code here:
        VentanaAggUsuario ventanaAggUsuario = new VentanaAggUsuario(administrador);
        ventanaAggUsuario.setVentanaOpcionesAdmi(this);
        ventanaAggUsuario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonAggUsuario1ActionPerformed

    private void registroAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroAdministradorActionPerformed
        // TODO add your handling code here:
            VentanaRegistroAdministrador ventanaRegistroAdministrador = new VentanaRegistroAdministrador(administrador);
            ventanaRegistroAdministrador.setVentanaOpcionesAdmi(this);
            ventanaRegistroAdministrador.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_registroAdministradorActionPerformed



    private void botonActualizarUsuario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarUsuario2ActionPerformed
        // TODO add your handling code here:
        VentanaActualizarUsuario ventanaActualizarUsuario = new VentanaActualizarUsuario(administrador);
        ventanaActualizarUsuario.setVentanaOpcionesAdmi(this);
        ventanaActualizarUsuario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonActualizarUsuario2ActionPerformed

    private void botonRegistroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistroUsuarioActionPerformed
        // TODO add your handling code here:
        VentanaRegistroUsuarios ventanaRegistroUsuarios = new VentanaRegistroUsuarios();
        ventanaRegistroUsuarios.setVentanaOpcionesAdmi(this);
        ventanaRegistroUsuarios.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonRegistroUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        // Set the Nimbus look and feel
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        // If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         // For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         //
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaOpcionesAdmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaOpcionesAdmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaOpcionesAdmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaOpcionesAdmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        Administrador administrador=null;
        // Create and display the form
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaOpcionesAdmi(administrador).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables

    /**
     * Botón que permite al administrador actualizar la información de un usuario existente.
     */
    private javax.swing.JButton botonActualizarUsuario2;

    /**
     * Botón que permite al administrador agregar un nuevo usuario al sistema.
     */
    private javax.swing.JButton botonAggUsuario1;

    /**
     * Botón que permite al administrador eliminar un usuario existente del sistema.
     */
    private javax.swing.JButton botonEliminarUsuario;

    /**
     * Botón que permite al administrador acceder al registro de movimientos de los usuarios.
     */
    private javax.swing.JButton botonRegistroUsuario;

    /**
     * Botón que permite al administrador salir de la ventana actual y cerrar sesión.
     */
    private javax.swing.JButton botonSalir;

    /**
     * Etiqueta que muestra un fondo decorativo en la ventana, utilizado para diseño visual.
     */
    private javax.swing.JLabel fondo;

    /**
     * Botón que permite al administrador acceder al registro de movimientos administrativos.
     */
    private javax.swing.JButton registroAdministrador;

    /**
     * Etiqueta que muestra el texto "Movimientos", indicando la sección de registro de actividades.
     */
    private javax.swing.JLabel textoMovimientos;

// End of variables declaration//GEN-END:variables

}
