/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ve.edu.ucab.lab.Vista;

import ve.edu.ucab.lab.Controladores.ControladorCreadorDeRutasDeEjecutable;
import ve.edu.ucab.lab.Controladores.ControladorDepositoRetiro;
import ve.edu.ucab.lab.Controladores.ControladorSaldoCorrecto;
import ve.edu.ucab.lab.modelo.Cliente;


/**
 * La clase VentanaCantidadARetirar representa una ventana en la cual el usuario
 * puede ingresar la cantidad de dinero que desea retirar. A través de esta ventana,
 * el usuario puede validar la cantidad a retirar y proceder con la transacción.
 *
 * @author Camila Best
 * @version 2.25.2
 */
public class VentanaCantidadARetirar extends javax.swing.JFrame {
    /**
     * Ventana de retiro rápido asociada a la ventana actual.
     */
    private VentanaRetiroRapido ventanaRetiroRapido;

    /**
     * Monto que el usuario desea retirar.
     */
    private double datMonto;

    /**
     * Cliente asociado a la transacción de retiro.
     */
    private Cliente cliente;

    private String rutaImagenes;

    private ControladorCreadorDeRutasDeEjecutable rutasDeEjecutable;

    /**
     * Establece la ventana de retiro rápido.
     *
     * @param ventanaRetiroRapido Ventana de retiro rápido.
     */
    public void setVentanaRetiroRapido(VentanaRetiroRapido ventanaRetiroRapido) {
        this.ventanaRetiroRapido = ventanaRetiroRapido;
    }

    /**
     * Constructor de la clase, inicializa la ventana con el cliente.
     *
     * @param cliente Cliente asociado al retiro.
     */
    public VentanaCantidadARetirar(Cliente cliente) {
        initComponents();
        setLocationRelativeTo(null);
        this.cliente = cliente;
    }

    public void archivito(String rutaimg,String png){
        rutasDeEjecutable=new ControladorCreadorDeRutasDeEjecutable("",rutaimg,"",png);
        rutasDeEjecutable.rutas();
        rutaImagenes=rutasDeEjecutable.getRutaImagenes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textIngreseMonto = new javax.swing.JLabel();
        datoMonto = new javax.swing.JTextField();
        botonVolver = new javax.swing.JButton();
        botonSiguiente = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RápidoCash");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textIngreseMonto.setFont(new java.awt.Font("Roboto Black", 0, 33)); // NOI18N
        textIngreseMonto.setForeground(new java.awt.Color(255, 255, 255));
        textIngreseMonto.setText("INGRESE EL NÚMERO DEL MONTO A RETIRAR");
        getContentPane().add(textIngreseMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 700, 80));

        datoMonto.setBackground(new java.awt.Color(53, 51, 205));
        datoMonto.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        datoMonto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        datoMonto.setBorder(null);
        getContentPane().add(datoMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 230, 80));

        botonVolver.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(botonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 150, 60));

        botonSiguiente.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonSiguiente.setText("Siguiente");
        botonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(botonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, 150, 60));

        archivito("src/main/java/Imagenes/Fondo.png","Fondo.png");
        fondo.setIcon(new javax.swing.ImageIcon(rutaImagenes)); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Acción realizada cuando se presiona el botón "Volver" para regresar
     * a la ventana de retiro rápido.
     *
     * @param evt Evento de acción del botón "Volver".
     */
    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        ventanaRetiroRapido.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonVolverActionPerformed

    /**
     * Acción realizada cuando se presiona el botón "Siguiente" para proceder
     * con el retiro, tras verificar que el monto sea válido.
     *
     * @param evt Evento de acción del botón "Siguiente".
     */
    private void botonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiguienteActionPerformed
        ControladorSaldoCorrecto saldoRetirar = new ControladorSaldoCorrecto(datoMonto.getText());
        saldoRetirar.confirmarSaldo();
        if (saldoRetirar.errorMonto()){
            datMonto = Double.parseDouble(datoMonto.getText());
            ControladorDepositoRetiro retirar = new ControladorDepositoRetiro(cliente, datMonto);
            retirar.retiro();
            if (retirar.montoEfectivo()){
                VentanaVerificarId ventanaVerificarId = new VentanaVerificarId(datMonto, cliente);
                ventanaVerificarId.setVisible(true);
                this.setVisible(false);
            }
            datoMonto.setText("");
        }
        else {
            datoMonto.setText("");
        }
    }//GEN-LAST:event_botonSiguienteActionPerformed

    /**
     * Método principal para ejecutar la ventana de cantidad a retirar.
     *
     * @param args Los argumentos de línea de comandos.
     */

    public static void main(String args[]) {
        Cliente cliente = null;
        // Crear y mostrar la ventana
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCantidadARetirar(cliente).setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    /**
     * Botón que permite al usuario proceder con la acción de retiro.
     */
    private javax.swing.JButton botonSiguiente;

    /**
     * Botón que permite al usuario volver a la ventana anterior.
     */
    private javax.swing.JButton botonVolver;

    /**
     * Campo de texto donde el usuario ingresa el monto a retirar.
     */
    private javax.swing.JTextField datoMonto;

    /**
     * Fondo de la ventana que contiene el diseño de la interfaz de usuario.
     */
    private javax.swing.JLabel fondo;

    /**
     * Etiqueta que indica al usuario que ingrese el monto a retirar.
     */
    private javax.swing.JLabel textIngreseMonto;
// End of variables declaration//GEN-END:variables

}
