/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ve.edu.ucab.lab.Vista;

import ve.edu.ucab.lab.Controladores.ControladorCambiarSaldoBaseDeDatos;
import ve.edu.ucab.lab.Controladores.ControladorCreadorDeRutasDeEjecutable;
import ve.edu.ucab.lab.modelo.Cliente;

/**
 * VentanaOpcionesUsua es la clase que representa la ventana de opciones del usuario.
 * En esta ventana, el usuario puede realizar diversas operaciones como consultar saldo,
 * realizar depósitos, hacer retiros rápidos, consultar movimientos y cambiar su PIN.
 *
 * @author Camila Best
 * @version 2.25.2
 */

public class VentanaOpcionesUsua extends javax.swing.JFrame {

    /**
     * Ventana de acceso del usuario que permite regresar al inicio.
     */
    private VentanaAccesoUsuario ventanaAccesoUsuario;

    /**
     * Instancia única de la ventana de opciones del usuario.
     */
    private static VentanaOpcionesUsua instancia;

    /**
     * El cliente asociado a la ventana de opciones.
     */
    private static Cliente cliente;

    private String rutaImagenes;

    private ControladorCreadorDeRutasDeEjecutable rutasDeEjecutable;

    /**
     * Establece la ventana de acceso del usuario.
     *
     * @param ventanaAccesoUsuario Ventana de acceso del usuario.
     */
    public void setVentanaAccesoUsuario(VentanaAccesoUsuario ventanaAccesoUsuario) {
        this.ventanaAccesoUsuario = ventanaAccesoUsuario;
    }

    /**
     * Obtiene la instancia única de la ventana de opciones del usuario.
     *
     * @return La instancia única de la ventana.
     */
    public static VentanaOpcionesUsua getInstance() {
        if (instancia == null) {
            instancia = new VentanaOpcionesUsua(cliente);
        }
        return instancia;
    }

    /**
     * Constructor que inicializa la ventana de opciones del usuario.
     * Coloca la ventana en el centro de la pantalla.
     *
     * @param cliente El cliente asociado a la ventana de opciones.
     */
    public VentanaOpcionesUsua(Cliente cliente) {
        initComponents();
        setLocationRelativeTo(null);
        this.cliente = cliente;
    }

    public void archivito(String rutaimg,String png){
        rutasDeEjecutable=new ControladorCreadorDeRutasDeEjecutable("",rutaimg,"",png);
        rutasDeEjecutable.rutas();
        rutaImagenes=rutasDeEjecutable.getRutaImagenes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextoElijaOpe = new javax.swing.JLabel();
        BotonCambiarPin = new javax.swing.JButton();
        BotonConsultarSaldo = new javax.swing.JButton();
        BotonDeposito = new javax.swing.JButton();
        BotonRetiroRap = new javax.swing.JButton();
        BotonConsultarMovimientos = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RápidoCash");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(51, 153, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextoElijaOpe.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        TextoElijaOpe.setForeground(new java.awt.Color(255, 255, 255));
        TextoElijaOpe.setText("ELIJA LA OPERACION A REALIZAR");
        getContentPane().add(TextoElijaOpe, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 660, 100));

        BotonCambiarPin.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        BotonCambiarPin.setText("Cambiar Pin");
        BotonCambiarPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCambiarPinActionPerformed(evt);
            }
        });
        getContentPane().add(BotonCambiarPin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 290, 70));

        BotonConsultarSaldo.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        BotonConsultarSaldo.setText("Consultar Saldo");
        BotonConsultarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarSaldoActionPerformed(evt);
            }
        });
        getContentPane().add(BotonConsultarSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 290, 70));

        BotonDeposito.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        BotonDeposito.setText("Depositar");
        BotonDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDepositoActionPerformed(evt);
            }
        });
        getContentPane().add(BotonDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 290, 70));

        BotonRetiroRap.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        BotonRetiroRap.setText("Retiro Rápido");
        BotonRetiroRap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRetiroRapActionPerformed(evt);
            }
        });
        getContentPane().add(BotonRetiroRap, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 290, 70));

        BotonConsultarMovimientos.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        BotonConsultarMovimientos.setText("Consultar Movimientos");
        BotonConsultarMovimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarMovimientosActionPerformed(evt);
            }
        });
        getContentPane().add(BotonConsultarMovimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 290, 70));

        BotonSalir.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        BotonSalir.setText("Salir");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 290, 70));

        archivito("src/main/java/Imagenes/Fondo.png","Fondo.png");
        Fondo.setIcon(new javax.swing.ImageIcon(rutaImagenes)); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento que se ejecuta cuando el usuario hace clic en el botón "Salir".
     * Regresa a la ventana de acceso del usuario y cierra la ventana actual.
     *
     * @param evt El evento que ocurre al hacer clic en el botón.
     */

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        ControladorCambiarSaldoBaseDeDatos nuevoSaldo=new ControladorCambiarSaldoBaseDeDatos(cliente);
        nuevoSaldo.cagarNuevosDatos();
        VentanaAccesoUsuario ventana = VentanaAccesoUsuario.getInstance();
        ventana.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_BotonSalirActionPerformed

    /**
     * Evento que se ejecuta cuando el usuario hace clic en el botón "Consultar Saldo".
     * Abre la ventana para consultar el saldo del usuario y cierra la ventana actual.
     *
     * @param evt El evento que ocurre al hacer clic en el botón.
     */

    private void botonConsultarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConsultarSaldoActionPerformed
        // TODO add your handling code here:
        VentanaSaldo ventanaSaldo = new VentanaSaldo(cliente);
        ventanaSaldo.setVentanaOpcionesUsua(this);
        ventanaSaldo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonConsultarSaldoActionPerformed

    /**
     * Evento que se ejecuta cuando el usuario hace clic en el botón "Cambiar PIN".
     * Abre la ventana para cambiar el PIN del usuario y cierra la ventana actual.
     *
     * @param evt El evento que ocurre al hacer clic en el botón.
     */

    private void botonCambiarPinActionPerformed(java.awt.event.ActionEvent evt) {                                                
        VentanaCambiarPinUsuario ventanaPin= new VentanaCambiarPinUsuario(cliente);
        ventanaPin.setVentanaOpcionUsuario(this);
        ventanaPin.setVisible(true);
        this.setVisible(false);

    }

    /**
     * Evento que se ejecuta cuando el usuario hace clic en el botón "Depositar".
     * Abre la ventana para realizar un depósito y cierra la ventana actual.
     *
     * @param evt El evento que ocurre al hacer clic en el botón.
     */

    private void botonDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDepositoActionPerformed
        // TODO add your handling code here:
        VentanaDeposito ventanaDeposito= new VentanaDeposito(cliente);
        ventanaDeposito.setVentanaOpcionesUsua(this);
        ventanaDeposito.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonDepositoActionPerformed

    /**
     * Evento que se ejecuta cuando el usuario hace clic en el botón "Retiro Rápido".
     * Abre la ventana para realizar un retiro rápido y cierra la ventana actual.
     *
     * @param evt El evento que ocurre al hacer clic en el botón.
     */

    private void botonRetiroRapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRetiroRapActionPerformed
        // TODO add your handling code here:
        VentanaRetiroRapido ventanaRetiroRap= new VentanaRetiroRapido(cliente);
        ventanaRetiroRap.setVentanaOpcionesUsua(this);
        ventanaRetiroRap.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonRetiroRapActionPerformed

    /**
     * Evento que se ejecuta cuando el usuario hace clic en el botón "Consultar Movimientos".
     * Abre la ventana para consultar los movimientos del usuario y cierra la ventana actual.
     *
     * @param evt El evento que ocurre al hacer clic en el botón.
     */

    private void botonConsultarMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConsultarMovimientosActionPerformed
        // TODO add your handling code here:
        VentanaMovimientos ventanaMovimientos= new VentanaMovimientos(cliente);
        ventanaMovimientos.setVentanaOpcionesUsua(this);
        ventanaMovimientos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonConsultarMovimientosActionPerformed

    /**
     * Método principal que configura el aspecto y la ejecución de la ventana de opciones del usuario.
     *
     * @param args Los argumentos de la línea de comandos.
     */

    public static void main(String args[]) {
        // Set the Nimbus look and feel
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        // If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         // For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         //
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaOpcionesUsua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaOpcionesUsua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaOpcionesUsua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaOpcionesUsua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        Cliente cliente = null;


        // Create and display the form
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaOpcionesUsua(cliente).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    /**
     * Botón que permite cambiar el PIN del usuario.
     */
    private javax.swing.JButton BotonCambiarPin;

    /**
     * Botón que permite consultar los movimientos del usuario.
     */
    private javax.swing.JButton BotonConsultarMovimientos;

    /**
     * Botón que permite consultar el saldo del usuario.
     */
    private javax.swing.JButton BotonConsultarSaldo;

    /**
     * Botón que permite realizar un depósito en la cuenta del usuario.
     */
    private javax.swing.JButton BotonDeposito;

    /**
     * Botón que permite realizar un retiro rápido de la cuenta del usuario.
     */
    private javax.swing.JButton BotonRetiroRap;

    /**
     * Botón que permite salir de la ventana de opciones y regresar a la ventana de acceso del usuario.
     */
    private javax.swing.JButton BotonSalir;

    /**
     * Etiqueta de fondo que se utiliza para la apariencia de la ventana.
     */
    private javax.swing.JLabel Fondo;

    /**
     * Etiqueta que muestra el mensaje de "Elija una operación".
     */
    private javax.swing.JLabel TextoElijaOpe;

    // End of variables declaration//GEN-END:variables
}
