/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ve.edu.ucab.lab.Vista;

import ve.edu.ucab.lab.Controladores.ControladorCorreoCorrecto;
import ve.edu.ucab.lab.Controladores.ControladorCreadorDeRutasDeEjecutable;
import ve.edu.ucab.lab.Controladores.ControladorDatosPalabrasCorrectos;
import ve.edu.ucab.lab.Controladores.ControladorOlvidarContraAdmin;

/**
 * VentanaRecuperarPinAdmin es la clase que representa la ventana para que el administrador
 * recupere el PIN. En esta ventana, el administrador puede interactuar con los campos para
 * recuperar un PIN en caso de ser necesario. Además, tiene un botón para volver a la ventana
 * principal de administración.
 *
 * @author Camila Best
 * @version 2.28.6
 */

public class VentanaRecuperarPinAdmin extends javax.swing.JFrame {

    /**
     * La ventana de administración asociada, a la que se vuelve después de realizar
     * una acción en esta ventana.
     */
    private VentanaAdmin ventanaAdmin;

    private String rutaImagenes;

    private ControladorCreadorDeRutasDeEjecutable rutasDeEjecutable;

    /**
     * Establece la ventana de administración para poder regresar a ella.
     *
     * @param ventanaAdmin La ventana de administración asociada.
     */
    public void setVentanaAdmin(VentanaAdmin ventanaAdmin) {
        this.ventanaAdmin = ventanaAdmin;
    }

    /**
     * Constructor que inicializa la ventana para recuperar el PIN del administrador.
     * Coloca la ventana en el centro de la pantalla.
     */
    public VentanaRecuperarPinAdmin() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public void archivito(String rutaimg,String png){
        rutasDeEjecutable=new ControladorCreadorDeRutasDeEjecutable("",rutaimg,"",png);
        rutasDeEjecutable.rutas();
        rutaImagenes=rutasDeEjecutable.getRutaImagenes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        TituloRapidoCash = new javax.swing.JLabel();
        ImagenDinero = new javax.swing.JLabel();
        textoRecuperarPin = new javax.swing.JLabel();
        textUsuario = new javax.swing.JLabel();
        textPin = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        botonRecuperar1 = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();
        ImagenCiudad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RápidoCash");
        setPreferredSize(new java.awt.Dimension(830, 501));
        setResizable(false);

        fondo.setBackground(new java.awt.Color(255, 255, 255));

        TituloRapidoCash.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        TituloRapidoCash.setText("RápidoCash");

        archivito("src/main/java/Imagenes/Dinero.png","Dinero.png");
        ImagenDinero.setIcon(new javax.swing.ImageIcon(rutaImagenes)); // NOI18N

        textoRecuperarPin.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        textoRecuperarPin.setText("RECUPERAR PIN ADMINISTRADOR");

        textUsuario.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        textUsuario.setText("USUARIO");

        textPin.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        textPin.setText("CORREO ELECTRÓNICO");

        jTextField1.setBorder(null);

        jTextField2.setBorder(null);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        botonRecuperar1.setBackground(new java.awt.Color(204, 204, 204));
        botonRecuperar1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonRecuperar1.setText("Recuperar");
        botonRecuperar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRecuperar1ActionPerformed(evt);
            }
        });

        botonVolver.setBackground(new java.awt.Color(204, 204, 204));
        botonVolver.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        archivito("src/main/java/Imagenes/CiudadPequeña.png","CiudadPequeña.png");
        ImagenCiudad.setIcon(new javax.swing.ImageIcon(rutaImagenes)); // NOI18N

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textPin)
                            .addComponent(textUsuario)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addComponent(TituloRapidoCash)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ImagenDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textoRecuperarPin)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(botonRecuperar1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)))
                .addComponent(ImagenCiudad))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TituloRapidoCash)
                        .addGap(32, 32, 32))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(ImagenDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(textoRecuperarPin)
                .addGap(35, 35, 35)
                .addComponent(textUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textPin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonRecuperar1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
            .addGroup(fondoLayout.createSequentialGroup()
                .addComponent(ImagenCiudad)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento que se ejecuta cuando el administrador hace clic en el botón "Recuperar".
     * Actualmente no tiene implementada ninguna acción.
     *
     * @param evt El evento que ocurre al hacer clic en el botón.
     */

    private void botonRecuperar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRecuperar1ActionPerformed
        ControladorDatosPalabrasCorrectos nombreCorrecto=new ControladorDatosPalabrasCorrectos(jTextField1.getText(),
                "Nombre de Usuario");
        nombreCorrecto.confirmarPalabrasCorrectas();
        ControladorCorreoCorrecto correo=new ControladorCorreoCorrecto(jTextField2.getText());
        correo.confirmarCorreo();
        if (nombreCorrecto.errorCadena() && correo.correoCorrecto()){
            ControladorOlvidarContraAdmin recuperarContrasenia=new ControladorOlvidarContraAdmin(
                    jTextField1.getText(),jTextField2.getText());
            recuperarContrasenia.cambioContrasenia();
            if (recuperarContrasenia.esResultado()){
                jTextField1.setText(recuperarContrasenia.getNombreUsuario());
                jTextField2.setText(recuperarContrasenia.getCorreoElectronico());
                VentanaPinRecuperado ventanaPinRecuperado = new VentanaPinRecuperado(recuperarContrasenia.getAdmin());
                ventanaPinRecuperado.setVentanaRecuperarPin(this);
                ventanaPinRecuperado.setVisible(true);
                this.setVisible(false);
            }
            else {
                jTextField1.setText(recuperarContrasenia.getNombreUsuario());
                jTextField2.setText(recuperarContrasenia.getCorreoElectronico());
            }

        }
        else {
            if (!nombreCorrecto.errorCadena()){
                jTextField1.setText(" ");
            }
            if(!correo.correoCorrecto()){
                jTextField2.setText(" ");
            }

        }

    }//GEN-LAST:event_botonRecuperar1ActionPerformed

    /**
     * Evento que se ejecuta cuando el administrador hace clic en el botón "Volver".
     * Regresa a la ventana principal de administración y cierra la ventana actual.
     *
     * @param evt El evento que ocurre al hacer clic en el botón.
     */
    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        // TODO add your handling code here:
        ventanaAdmin.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_botonVolverActionPerformed

    /**
     * Método principal que configura el aspecto y la ejecución de la ventana para
     * recuperar el PIN del administrador.
     *
     * @param args Los argumentos de la línea de comandos.
     */

    public static void main(String args[]) {
        // Set the Nimbus look and feel
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        //If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         // For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         //
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRecuperarPinAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRecuperarPinAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRecuperarPinAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRecuperarPinAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        // Create and display the form
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRecuperarPinAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    /**
     * Imagen de la ciudad que se muestra en la ventana.
     */
    private javax.swing.JLabel ImagenCiudad;

    /**
     * Imagen relacionada con dinero que se muestra en la ventana.
     */
    private javax.swing.JLabel ImagenDinero;

    /**
     * Título que aparece en la ventana, indicando que es la ventana de "RapidoCash".
     */
    private javax.swing.JLabel TituloRapidoCash;

    /**
     * Botón para realizar la recuperación del PIN.
     */
    private javax.swing.JButton botonRecuperar1;

    /**
     * Botón que permite al administrador regresar a la ventana principal de administración.
     */
    private javax.swing.JButton botonVolver;

    /**
     * Panel de fondo de la ventana.
     */
    private javax.swing.JPanel fondo;

    /**
     * Separador utilizado en la ventana para mejorar la disposición visual.
     */
    private javax.swing.JSeparator jSeparator1;

    /**
     * Otro separador utilizado en la ventana para la disposición visual.
     */
    private javax.swing.JSeparator jSeparator2;

    /**
     * Campo de texto que permite ingresar el nombre de usuario
     * para la recuperación del PIN.
     */
    private javax.swing.JTextField jTextField1;

    /**
     * Campo de texto que permite ingresar el correo necesario para la recuperación del PIN.
     */
    private javax.swing.JTextField jTextField2;

    /**
     * Etiqueta que indica el campo para ingresar el PIN.
     */
    private javax.swing.JLabel textPin;

    /**
     * Etiqueta que indica el campo para ingresar el nombre de usuario o identificador.
     */
    private javax.swing.JLabel textUsuario;

    /**
     * Etiqueta que da el título de la ventana, indicando que se trata de la recuperación del PIN.
     */
    private javax.swing.JLabel textoRecuperarPin;
    // End of variables declaration//GEN-END:variables
}
