/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ve.edu.ucab.lab.Vista;

import ve.edu.ucab.lab.Controladores.ControladorDepositoRetiro;
import ve.edu.ucab.lab.Controladores.ControladorLlenarBaseDatosMovimientosBancarios;
import ve.edu.ucab.lab.Controladores.ControladorSaldoCorrecto;
import ve.edu.ucab.lab.modelo.Cliente;
import ve.edu.ucab.lab.modelo.Transacciones;

import java.time.LocalDate;

/**
 * La clase VentanaDeposito permite a los usuarios realizar depósitos en su cuenta bancaria.
 * Esta ventana está asociada a un cliente específico y realiza las acciones necesarias para
 * procesar un depósito, validar el monto y registrar la transacción en la base de datos.
 *
 * @author Camila Best
 * @version 2.25.2
 */

public class VentanaDeposito extends javax.swing.JFrame {

    /**
     * Ventana de opciones del usuario a la que se volverá después de realizar la operación.
     */
    private VentanaOpcionesUsua ventanaOpcionesUsua;

    /**
     * Cliente que realiza el depósito. Este objeto contiene la información del usuario y su cuenta.
     */
    private Cliente cliente;

    /**
     * Tipo de movimiento que se está realizando, en este caso es "depósito".
     */
    private String movimiento;

    /**
     * Fecha actual en la que se realiza el depósito.
     */
    private LocalDate fecha;

    /**
     * Monto a ser depositado por el cliente.
     */
    private double datMonto;

    /**
     * Establece la ventana de opciones del usuario.
     *
     * @param ventanaOpcionesUsua Instancia de la ventana de opciones del usuario.
     */
    public void setVentanaOpcionesUsua(VentanaOpcionesUsua ventanaOpcionesUsua) {
        this.ventanaOpcionesUsua = ventanaOpcionesUsua;
    }

    /**
     * Constructor de la clase. Inicializa la ventana y los valores de cliente, movimiento y fecha.
     *
     * @param cliente Cliente asociado con la ventana de depósito.
     */
    public VentanaDeposito(Cliente cliente) {
        initComponents();
        setLocationRelativeTo(null);
        this.cliente = cliente;
        movimiento = "deposito";
        fecha = LocalDate.now();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoBlanco = new javax.swing.JPanel();
        tituloDeposito = new javax.swing.JLabel();
        textoMonto = new javax.swing.JLabel();
        botonVolver = new javax.swing.JButton();
        botonRealizar = new javax.swing.JButton();
        datoMonto = new javax.swing.JTextField();
        textBs = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RápidoCash");
        setPreferredSize(new java.awt.Dimension(800, 501));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondoBlanco.setBackground(new java.awt.Color(204, 204, 255));

        tituloDeposito.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        tituloDeposito.setText("Deposito");

        textoMonto.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        textoMonto.setText("Monto");

        botonVolver.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        botonRealizar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonRealizar.setText("Realizar");
        botonRealizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRealizarActionPerformed(evt);
            }
        });

        datoMonto.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        datoMonto.setText("00,00");

        textBs.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textBs.setText("Bs");

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel1.setText("INGRESE EL MONTO QUE DESEA DEPOSITAR");

        javax.swing.GroupLayout fondoBlancoLayout = new javax.swing.GroupLayout(fondoBlanco);
        fondoBlanco.setLayout(fondoBlancoLayout);
        fondoBlancoLayout.setHorizontalGroup(
            fondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoBlancoLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(botonRealizar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 394, Short.MAX_VALUE)
                .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(fondoBlancoLayout.createSequentialGroup()
                .addGroup(fondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoBlancoLayout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(textoMonto)
                        .addGap(39, 39, 39)
                        .addComponent(datoMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textBs))
                    .addGroup(fondoBlancoLayout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(tituloDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fondoBlancoLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fondoBlancoLayout.setVerticalGroup(
            fondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoBlancoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(tituloDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(105, 105, 105)
                .addGroup(fondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(datoMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoMonto)
                    .addComponent(textBs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addGroup(fondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonRealizar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        getContentPane().add(fondoBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que se ejecuta cuando se presiona el botón "Realizar".
     * Valida el monto y realiza el depósito, además de registrar la transacción.
     * Si hay un error en el monto, el campo se limpia para intentar de nuevo.
     *
     * @param evt Evento de acción del botón "Realizar".
     */

    private void botonRealizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRealizarActionPerformed
        ControladorSaldoCorrecto digitos=new ControladorSaldoCorrecto(datoMonto.getText());
        digitos.confirmarSaldo();
        if(digitos.errorMonto()){
            datMonto = Double.parseDouble(datoMonto.getText());
            ControladorDepositoRetiro depositar=new ControladorDepositoRetiro(cliente,datMonto);
            depositar.deposito();
            Transacciones deposito = new Transacciones(fecha,movimiento, cliente.getNombreCliente(),
                    cliente.getApellidoCliente(), cliente.getTelefonoCliente(),datMonto,
                    cliente.getCuenta().getTipoCuentaCliente(),"","");
            ControladorLlenarBaseDatosMovimientosBancarios movCliente=new ControladorLlenarBaseDatosMovimientosBancarios(deposito);
            movCliente.subirMovimientos();
            VentanaOpcionesUsua ventana = VentanaOpcionesUsua.getInstance();
            ventana.setVisible(true);
            this.setVisible(false);
        }
        else {
            datoMonto.setText("");
        }

    }//GEN-LAST:event_botonRealizarActionPerformed

    /**
     * Método que se ejecuta cuando se presiona el botón "Volver".
     * Vuelve a la ventana de opciones del usuario.
     *
     * @param evt Evento de acción del botón "Volver".
     */

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        // TODO add your handling code here:
        ventanaOpcionesUsua.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonVolverActionPerformed

    /**
     * Método principal para ejecutar la clase.
     *
     * @param args Argumentos de línea de comandos.
     */

    public static void main(String args[]) {
        //Set the Nimbus look and feel
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        // If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         // For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         //
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDeposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDeposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDeposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDeposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        Cliente cliente=null;
        // Create and display the form
        java.awt.EventQueue.invokeLater(() -> new VentanaDeposito(cliente).setVisible(true));
    }

    // Variables declaration - do not modify

    /**
     * Botón que permite realizar el depósito.
     */
    private javax.swing.JButton botonRealizar;

    /**
     * Botón que permite volver a la ventana de opciones del usuario.
     */
    private javax.swing.JButton botonVolver;

    /**
     * Campo de texto donde el usuario ingresa el monto que desea depositar.
     */
    private javax.swing.JTextField datoMonto;

    /**
     * Panel que sirve como contenedor principal para el contenido de la ventana.
     */
    private javax.swing.JPanel fondoBlanco;

    /**
     * Etiqueta de texto que se usa para mostrar información en la ventana.
     */
    private javax.swing.JLabel jLabel1;

    /**
     * Etiqueta que muestra el texto "Bs" para indicar la unidad monetaria en el campo de monto.
     */
    private javax.swing.JLabel textBs;

    /**
     * Etiqueta que muestra el texto "Monto" como título del campo donde se ingresa el monto a depositar.
     */
    private javax.swing.JLabel textoMonto;

    /**
     * Etiqueta que muestra el título "Depósito" en la ventana.
     */
    private javax.swing.JLabel tituloDeposito;

// End of variables declaration

}
