/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ve.edu.ucab.lab.Vista;

import ve.edu.ucab.lab.Controladores.ControladorCambiarSaldoBaseDeDatos;
import ve.edu.ucab.lab.Controladores.ControladorCreadorDeRutasDeEjecutable;
import ve.edu.ucab.lab.modelo.Cliente;

/**
 * La clase VentanaFinal representa la ventana final que se muestra al usuario cuando
 * ha completado una transacción o acción en la aplicación. Desde esta ventana, el
 * usuario puede elegir entre finalizar la sesión o regresar al menú de opciones.
 *
 * @author Camila Best
 * @version 2.28.6
 */
public class VentanaFinal extends javax.swing.JFrame {
    /**
     * Objeto que representa al cliente que está interactuando con la ventana final.
     */
    private Cliente cliente;

    private String rutaImagenes;

    private ControladorCreadorDeRutasDeEjecutable rutasDeEjecutable;

    /**
     * Constructor por defecto que inicializa los componentes de la ventana y
     * ajusta su ubicación en el centro de la pantalla.
     */
    public VentanaFinal(Cliente cliente) {
        initComponents();
        setLocationRelativeTo(null);
        this.cliente = cliente;

    }

    public void archivito(String rutaimg,String png){
        rutasDeEjecutable=new ControladorCreadorDeRutasDeEjecutable("",rutaimg,"",png);
        rutasDeEjecutable.rutas();
        rutaImagenes=rutasDeEjecutable.getRutaImagenes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Text = new javax.swing.JLabel();
        botonRegresarMenu = new javax.swing.JButton();
        BotonFinalizar = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Text.setFont(new java.awt.Font("Roboto Black", 0, 30)); // NOI18N
        Text.setForeground(new java.awt.Color(255, 255, 255));
        Text.setText("TRANSACCIÓN REALIZADA CON EXITO");
        getContentPane().add(Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 610, 96));

        botonRegresarMenu.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        botonRegresarMenu.setText("Regresar al menú");
        botonRegresarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarMenuActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegresarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 250, 60));

        BotonFinalizar.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        BotonFinalizar.setText("Salir");
        BotonFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFinalizarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 250, 60));

        archivito("src/main/java/Imagenes/Fondo.png","Fondo.png");
        Fondo.setIcon(new javax.swing.ImageIcon(rutaImagenes)); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Este método se ejecuta cuando el usuario hace clic en el botón "Finalizar".
     * Cierra la ventana actual y abre la ventana de acceso de usuario.
     *
     * @param evt El evento que dispara la acción de hacer clic en el botón.
     */

    private void botonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonFinalizarActionPerformed
        ControladorCambiarSaldoBaseDeDatos nuevoSaldo=new ControladorCambiarSaldoBaseDeDatos(cliente);
        nuevoSaldo.cagarNuevosDatos();
        VentanaAccesoUsuario ventana = VentanaAccesoUsuario.getInstance();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonFinalizarActionPerformed

    /**
     * Este método se ejecuta cuando el usuario hace clic en el botón "Regresar al menú".
     * Cierra la ventana actual y abre la ventana de opciones del usuario.
     *
     * @param evt El evento que dispara la acción de hacer clic en el botón.
     */

    private void botonRegresarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarMenuActionPerformed
        // TODO add your handling code here:
        VentanaOpcionesUsua ventana = VentanaOpcionesUsua.getInstance();
        ventana.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_botonRegresarMenuActionPerformed

    /**
     * Método principal que inicializa y muestra la ventana final.
     *
     * @param args Los argumentos de línea de comandos.
     */

    public static void main(String args[]) {
        // Set the Nimbus look and feel
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        // If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         // For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         //
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        Cliente cliente=null;
        // Create and display the form
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaFinal(cliente).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    /**
     * Botón para finalizar la sesión o la acción actual.
     * Al hacer clic en este botón, se cierra la ventana y se abre la ventana de acceso de usuario.
     */
    private javax.swing.JButton BotonFinalizar;

    /**
     * Etiqueta (JLabel) que representa el fondo de la ventana final.
     * Esta etiqueta generalmente se utiliza para mostrar un fondo o imagen.
     */
    private javax.swing.JLabel Fondo;

    /**
     * Etiqueta (JLabel) que muestra un texto en la ventana final.
     * Usualmente se utiliza para proporcionar información o instrucciones al usuario.
     */
    private javax.swing.JLabel Text;

    /**
     * Botón para regresar al menú de opciones del usuario.
     * Al hacer clic en este botón, se cierra la ventana actual y se abre la ventana de opciones del usuario.
     */
    private javax.swing.JButton botonRegresarMenu;
// End of variables declaration//GEN-END:variables

}
