/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ve.edu.ucab.lab.Vista;

import ve.edu.ucab.lab.Controladores.ControladorCreadorDeRutasDeEjecutable;
import ve.edu.ucab.lab.Controladores.ControladorMostrarMovimientosClientes;
import ve.edu.ucab.lab.modelo.Cliente;

/**
 * VentanaMovimientos es la clase que representa la ventana que muestra los movimientos
 * de un cliente en la aplicación. Esta ventana permite ver la lista de movimientos
 * asociados a una cuenta de cliente.
 *
 * @author Camila Best
 * @version 2.25.2
 */

public class VentanaMovimientos extends javax.swing.JFrame {

    /**
     * Ventana de opciones del usuario, donde se puede regresar a las opciones principales.
     */
    private VentanaOpcionesUsua ventanaOpcionesUsua;

    /**
     * Objeto cliente asociado que tiene la información sobre el usuario que se está visualizando.
     */
    private Cliente cliente;

    /**
     * Controlador que maneja la carga y visualización de los movimientos del cliente.
     */
    private ControladorMostrarMovimientosClientes tablaMovimientosCliente;

    private String rutaImagenes;

    private ControladorCreadorDeRutasDeEjecutable rutasDeEjecutable;

    /**
     * Establece la ventana de opciones del usuario a la que se puede regresar.
     *
     * @param ventanaOpcionesUsua Ventana que contiene las opciones del usuario.
     */
    public void setVentanaOpcionesUsua(VentanaOpcionesUsua ventanaOpcionesUsua) {
        this.ventanaOpcionesUsua = ventanaOpcionesUsua;
        //tablaMovimientosCliente.mostrarMovimientos();  // Descomentado si es necesario
    }

    /**
     * Constructor que inicializa la ventana de movimientos del cliente.
     *
     * @param cliente El cliente cuyas transacciones se van a mostrar.
     */
    public VentanaMovimientos(Cliente cliente) {
        initComponents();
        setLocationRelativeTo(null);
        this.cliente = cliente;
        tablaMovimientosCliente = new ControladorMostrarMovimientosClientes(cliente, tablaMovimientos);
        tablaMovimientosCliente.mostrarMovimientos();
        setVisible(true);
    }

    public void archivito(String rutaimg,String png){
        rutasDeEjecutable=new ControladorCreadorDeRutasDeEjecutable("",rutaimg,"",png);
        rutasDeEjecutable.rutas();
        rutaImagenes=rutasDeEjecutable.getRutaImagenes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoMovimientos = new javax.swing.JLabel();
        scrollTablaMovimientos = new javax.swing.JScrollPane();
        tablaMovimientos = new javax.swing.JTable();
        botonVolver = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RápidoCash");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textoMovimientos.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        textoMovimientos.setForeground(new java.awt.Color(255, 255, 255));
        textoMovimientos.setText("Movimientos bancarios ");
        getContentPane().add(textoMovimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        scrollTablaMovimientos.setBackground(new java.awt.Color(204, 204, 204));

        tablaMovimientos.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        tablaMovimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha", "Cuenta", "Monto", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollTablaMovimientos.setViewportView(tablaMovimientos);

        getContentPane().add(scrollTablaMovimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 680, 140));

        botonVolver.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(botonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, 160, 60));

        archivito("src/main/java/Imagenes/Fondo.png","Fondo.png");
        fondo.setIcon(new javax.swing.ImageIcon(rutaImagenes)); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento que se ejecuta cuando se hace clic en el botón "Volver".
     * Este método regresa a la ventana de opciones del usuario.
     *
     * @param evt El evento que ocurre al hacer clic en el botón.
     */

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        // TODO add your handling code here:
        ventanaOpcionesUsua.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonVolverActionPerformed

    /**
     * Método principal que configura el aspecto y la ejecución de la ventana de movimientos.
     *
     * @param args Los argumentos de la línea de comandos.
     */

    public static void main(String args[]) {
        // Set the Nimbus look and feel
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        // If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         // For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         //
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        Cliente cliente=null;
        // Create and display the form
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMovimientos(cliente).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    /**
     * Botón que permite regresar a la ventana de opciones del usuario.
     */
    private javax.swing.JButton botonVolver;

    /**
     * Etiqueta de fondo que se utiliza para la apariencia de la ventana.
     */
    private javax.swing.JLabel fondo;

    /**
     * Componente de desplazamiento para la tabla de movimientos.
     */
    private javax.swing.JScrollPane scrollTablaMovimientos;

    /**
     * Tabla que muestra los movimientos del cliente.
     */
    private javax.swing.JTable tablaMovimientos;

    /**
     * Etiqueta que indica la sección de los movimientos del cliente.
     */
    private javax.swing.JLabel textoMovimientos;
    // End of variables declaration//GEN-END:variables
}
