package ve.edu.ucab.lab.Vista;

import ve.edu.ucab.lab.Controladores.ActualizarUsuario;
import ve.edu.ucab.lab.Controladores.ControladorActualiazarClientesDatosCorrectos;
import ve.edu.ucab.lab.Controladores.ControladorCreadorDeRutasDeEjecutable;
import ve.edu.ucab.lab.modelo.Administrador;

import javax.swing.*;
import java.awt.*;
import java.io.IOException;

/**
 * Clase que representa la ventana de actualización de datos de un usuario.
 * Permite buscar, visualizar y modificar información de un usuario existente.
 *
 * @author Camila Best
 * @author Daniel Agudelo
 * @version 2.25.2
 */
public class VentanaActualizarUsuario extends javax.swing.JFrame {

    /**
     * Ventana de opciones administrativas a la que se regresa después de actualizar los datos.
     */
    private VentanaOpcionesAdmi ventanaOpcionesAdmi;
    /**
     * Objeto que representa al administrador que realiza las modificaciones.
     */
    private Administrador administrador;

    private String rutaImagenes;

    private ControladorCreadorDeRutasDeEjecutable rutasDeEjecutable;


    /**
     * Establece la ventana anterior de opciones administrativas.
     *
     * @param ventanaOpcionesAdmi La ventana de opciones administrativas.
     */
    public void setVentanaOpcionesAdmi(VentanaOpcionesAdmi ventanaOpcionesAdmi) {
        this.ventanaOpcionesAdmi = ventanaOpcionesAdmi;
    }

    /**
     * Constructor que inicializa la ventana de actualización de usuario.
     * Configura la ubicación de la ventana en el centro de la pantalla.
     */
    public VentanaActualizarUsuario(Administrador administrador) {
        initComponents();
        setLocationRelativeTo(null);
        this.administrador=administrador;
    }

    public void archivito(String rutaimg,String png){
        rutasDeEjecutable=new ControladorCreadorDeRutasDeEjecutable("",rutaimg,"",png);
        rutasDeEjecutable.rutas();
        rutaImagenes=rutasDeEjecutable.getRutaImagenes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        TituloRapidoCash = new javax.swing.JLabel();
        botonActualizar = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();
        IconoDinero = new javax.swing.JLabel();
        textoBuscarUsuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numeroDeTelefono = new javax.swing.JTextField();
        textIngreseNumero = new javax.swing.JLabel();
        textNombre = new javax.swing.JLabel();
        nombreUsuario = new javax.swing.JTextField();
        textApellido = new javax.swing.JLabel();
        apellidoUsuario = new javax.swing.JTextField();
        botonBuscarUsuario = new javax.swing.JButton();
        textCedula = new javax.swing.JLabel();
        cedulaUsuario = new javax.swing.JTextField();
        textTelefono = new javax.swing.JLabel();
        telefonoUuario = new javax.swing.JTextField();
        textCorreo = new javax.swing.JLabel();
        tipoDeCuenta = new javax.swing.JTextField();
        textTipoDeCuenta = new javax.swing.JLabel();
        textEstadoDeCuenta = new javax.swing.JLabel();
        textPin = new javax.swing.JLabel();
        pinUsuario = new javax.swing.JTextField();
        correoUsuario1 = new javax.swing.JTextField();
        estadoDeCuenta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RápidoCash");
        setPreferredSize(new java.awt.Dimension(870, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fondo.setBackground(new java.awt.Color(204, 204, 255));

        TituloRapidoCash.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        TituloRapidoCash.setText("RápidoCash");

        botonActualizar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonActualizar.setText("Actualizar");
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });

        botonVolver.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        archivito("src/main/java/Imagenes/Dinero.png","Dinero.png");
        IconoDinero.setIcon(new javax.swing.ImageIcon(rutaImagenes)); // NOI18N

        textoBuscarUsuario.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        textoBuscarUsuario.setText("BUSCAR USUARIO PARA ACTUALIZAR");

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel2.setText("Actualizar Uuario");

        numeroDeTelefono.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        textIngreseNumero.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textIngreseNumero.setText("Ingrese el número de teléfono");

        textNombre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textNombre.setText("Nombre :");

        textApellido.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textApellido.setText("Apellido:");

        botonBuscarUsuario.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        botonBuscarUsuario.setText("Buscar");
        botonBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarUsuarioActionPerformed(evt);
            }
        });

        textCedula.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textCedula.setText("Cédula de identidad:");

        textTelefono.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textTelefono.setText("Télefono:");

        textCorreo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textCorreo.setText("Correo Electrónico:");

        textTipoDeCuenta.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textTipoDeCuenta.setText("Tipo de cuenta:");

        textEstadoDeCuenta.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textEstadoDeCuenta.setText("Estado de cuenta:");

        textPin.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textPin.setText("Pin:");

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addComponent(textIngreseNumero)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addComponent(botonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(107, 107, 107))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(numeroDeTelefono, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoBuscarUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(22, 22, 22)
                                .addComponent(botonBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textNombre)
                                    .addComponent(textApellido))
                                .addGap(75, 75, 75)
                                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(apellidoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textCedula)
                                    .addComponent(textTelefono))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cedulaUsuario)
                                    .addComponent(telefonoUuario, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)))
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addComponent(TituloRapidoCash)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IconoDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(56, 56, 56)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textCorreo)
                                    .addComponent(textPin)
                                    .addComponent(textEstadoDeCuenta))
                                .addGap(18, 18, 18)
                                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(fondoLayout.createSequentialGroup()
                                        .addComponent(pinUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                        .addGap(107, 107, 107))
                                    .addGroup(fondoLayout.createSequentialGroup()
                                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tipoDeCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                            .addComponent(estadoDeCuenta))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addComponent(textTipoDeCuenta)
                                .addGap(0, 0, Short.MAX_VALUE))))))
            .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fondoLayout.createSequentialGroup()
                    .addGap(613, 613, 613)
                    .addComponent(correoUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(112, Short.MAX_VALUE)))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(TituloRapidoCash))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(IconoDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(7, 7, 7)
                .addComponent(textoBuscarUsuario)
                .addGap(5, 5, 5)
                .addComponent(textIngreseNumero)
                .addGap(18, 18, 18)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroDeTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCorreo))
                .addGap(18, 18, 18)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNombre)
                    .addComponent(nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTipoDeCuenta)
                    .addComponent(tipoDeCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textApellido)
                    .addComponent(apellidoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textEstadoDeCuenta)
                    .addComponent(estadoDeCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cedulaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCedula)
                    .addComponent(textPin)
                    .addComponent(pinUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textTelefono)
                    .addComponent(telefonoUuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fondoLayout.createSequentialGroup()
                    .addGap(213, 213, 213)
                    .addComponent(correoUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(315, Short.MAX_VALUE)))
        );

        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents



    /**
     * Acción ejecutada al presionar el botón "Volver".
     * Retorna a la ventana de opciones administrativas.
     *
     * @param evt El evento de acción generado.
     */
    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {
        ventanaOpcionesAdmi.setVisible(true);
        this.setVisible(false);
    }

    /**
     * Acción ejecutada al presionar el botón "Actualizar".
     * Valida los datos ingresados en los campos de texto y actualiza la información del usuario.
     *
     * @param evt El evento de acción generado.
     */
    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {
        // Crear instancia de ActualizarUsuario
        ActualizarUsuario actualizarUsuario = new ActualizarUsuario();

        // Delegar toda la lógica de actualización a la clase ActualizarUsuario
        actualizarUsuario.gestionarActualizacionUsuario(
                nombreUsuario, // JTextField para el nombre
                apellidoUsuario, // JTextField para el apellido
                telefonoUuario, // JTextField para el teléfono
                cedulaUsuario, // JTextField para la cédula
                pinUsuario, // JTextField para el PIN
                correoUsuario1, // JTextField para el correo
                tipoDeCuenta, // JTextField para el tipo de cuenta
                estadoDeCuenta, // JTextField para el estado de cuenta
                administrador //Un objeto Administrador
        );
    }

    /**
     * Acción ejecutada al presionar el botón "Buscar Usuario".
     * Busca y carga la información del usuario en los campos de texto correspondientes.
     *
     * @param evt El evento de acción generado.
     */
    private void botonBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {
        String numeroTelefono = numeroDeTelefono.getText().trim();

        // Verificar que se haya ingresado un número de teléfono válido
        if (numeroTelefono.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un número de teléfono válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Llamar al método de ActualizarUsuario para buscar y actualizar los campos con la información
        ActualizarUsuario.buscarYActualizarCampos(numeroTelefono,
                new JTextField[]{pinUsuario, nombreUsuario, apellidoUsuario, cedulaUsuario, telefonoUuario, correoUsuario1, tipoDeCuenta, estadoDeCuenta});
    }

    /**
     * Método principal para ejecutar la ventana.
     *
     * @param args Los argumentos de la línea de comandos.
     */
    public static void main(String args[]) {
        // Set the Nimbus look and feel
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaActualizarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaActualizarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaActualizarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaActualizarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        Administrador administrador=null;
        //Create and display the form
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaActualizarUsuario(administrador).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    /**
     * Fondo de la ventana de actualización de usuario.
     */
    private javax.swing.JPanel Fondo;

    /**
     * Icono relacionado con dinero en la ventana de actualización.
     */
    private javax.swing.JLabel IconoDinero;

    /**
     * Título de la ventana, indicando la aplicación de "RapidoCash".
     */
    private javax.swing.JLabel TituloRapidoCash;

    /**
     * Campo de texto para ingresar el apellido del usuario.
     */
    private javax.swing.JTextField apellidoUsuario;

    /**
     * Botón para actualizar los datos del usuario.
     */
    private javax.swing.JButton botonActualizar;

    /**
     * Botón para buscar la información de un usuario.
     */
    private javax.swing.JButton botonBuscarUsuario;

    /**
     * Botón para volver a la ventana anterior de opciones administrativas.
     */
    private javax.swing.JButton botonVolver;

    /**
     * Campo de texto para ingresar la cédula del usuario.
     */
    private javax.swing.JTextField cedulaUsuario;

    /**
     * Campo de texto para ingresar el correo del usuario.
     */
    private javax.swing.JTextField correoUsuario1;

    /**
     * Campo de texto para ingresar el estado de cuenta del usuario.
     */
    private javax.swing.JTextField estadoDeCuenta;

    /**
     * Etiqueta para organizar la interfaz gráfica.
     */
    private javax.swing.JLabel jLabel2;

    /**
     * Campo de texto para ingresar el nombre del usuario.
     */
    private javax.swing.JTextField nombreUsuario;

    /**
     * Campo de texto para ingresar el número de teléfono del usuario.
     */
    private javax.swing.JTextField numeroDeTelefono;

    /**
     * Campo de texto para ingresar el PIN del usuario.
     */
    private javax.swing.JTextField pinUsuario;

    /**
     * Campo de texto para ingresar el teléfono del usuario.
     */
    private javax.swing.JTextField telefonoUuario;

    /**
     * Etiqueta para el apellido del usuario.
     */
    private javax.swing.JLabel textApellido;

    /**
     * Etiqueta para la cédula del usuario.
     */
    private javax.swing.JLabel textCedula;

    /**
     * Etiqueta para el correo del usuario.
     */
    private javax.swing.JLabel textCorreo;

    /**
     * Etiqueta para el estado de cuenta del usuario.
     */
    private javax.swing.JLabel textEstadoDeCuenta;

    /**
     * Etiqueta para ingresar el número de teléfono.
     */
    private javax.swing.JLabel textIngreseNumero;

    /**
     * Etiqueta para el nombre del usuario.
     */
    private javax.swing.JLabel textNombre;

    /**
     * Etiqueta para el PIN del usuario.
     */
    private javax.swing.JLabel textPin;

    /**
     * Etiqueta para el teléfono del usuario.
     */
    private javax.swing.JLabel textTelefono;

    /**
     * Etiqueta para el tipo de cuenta del usuario.
     */
    private javax.swing.JLabel textTipoDeCuenta;

    /**
     * Etiqueta para buscar un usuario.
     */
    private javax.swing.JLabel textoBuscarUsuario;

    /**
     * Campo de texto para el tipo de cuenta del usuario.
     */
    private javax.swing.JTextField tipoDeCuenta;

    // End of variables declaration//GEN-END:variables

}