/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ve.edu.ucab.lab.Vista;

import ve.edu.ucab.lab.Controladores.RegistroUsuarios;

/**
 * Clase que representa la ventana de registro de usuarios en el sistema.
 * Permite al administrador visualizar y gestionar el registro de usuarios.
 *
 * Esta clase extiende {@code javax.swing.JFrame} y utiliza componentes de Swing para
 * construir su interfaz gráfica.
 *
 * @author Camila Best
 * @version 2.25.2
 */
public class VentanaRegistroUsuarios extends javax.swing.JFrame {
    /**
     * Objeto que gestiona el registro de usuarios. Se encarga de la carga de datos desde el archivo
     * y su visualización en la tabla correspondiente.
     */
    private RegistroUsuarios registroUsuarios;
    /**
     * Ventana de opciones del administrador desde la cual se accede a esta ventana.
     */
        private VentanaOpcionesAdmi ventanaOpcionesAdmi;

    /**
     * Establece la ventana de opciones del administrador que invocó esta ventana.
     *
     * @param ventanaOpcionesAdmi la ventana de opciones del administrador
     */

    public void setVentanaOpcionesAdmi(VentanaOpcionesAdmi ventanaOpcionesAdmi) {
        this.ventanaOpcionesAdmi = ventanaOpcionesAdmi;
    }
    /**
     * Crea una nueva instancia de la ventana de registro de usuarios.
     */
    public VentanaRegistroUsuarios() {
        initComponents();
        setLocationRelativeTo(null);

        // Crear instancia de RegistroUsuarios y cargar datos
        registroUsuarios = new RegistroUsuarios(tablaDeMovimientos);
        registroUsuarios.cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        textRegistroUsuarios = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDeMovimientos = new javax.swing.JTable();
        botonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RápidoCash");
        setPreferredSize(new java.awt.Dimension(870, 501));
        setResizable(false);

        fondo.setBackground(new java.awt.Color(204, 204, 255));

        textRegistroUsuarios.setFont(new java.awt.Font("Roboto Black", 0, 34)); // NOI18N
        textRegistroUsuarios.setText("Registro de Movimientos de Usuarios");

        tablaDeMovimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", " Tipo de Movimiento", "Teléfono", "Nombre ", "Apellido", "Tipo de Cuenta", "Saldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaDeMovimientos.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tablaDeMovimientosAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tablaDeMovimientos);

        botonVolver.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(608, 608, 608)
                        .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(textRegistroUsuarios))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(textRegistroUsuarios)
                .addGap(72, 72, 72)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento que se ejecuta cuando se añade un ancestro a la tabla de movimientos.
     *
     * @param evt el evento de ancestro
     */

    private void tablaDeMovimientosAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tablaDeMovimientosAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaDeMovimientosAncestorAdded

    /**
     * Acción que se ejecuta al hacer clic en el botón "Volver".
     * Muestra la ventana de opciones del administrador y oculta la actual.
     *
     * @param evt el evento de acción
     */

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        // TODO add your handling code here:
        ventanaOpcionesAdmi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonVolverActionPerformed

    /**
     * Método principal para ejecutar la ventana de registro de usuarios.
     * Inicializa y muestra la interfaz gráfica.
     *
     * @param args argumentos de la línea de comandos
     */

    public static void main(String args[]) {
        // Set the Nimbus look and feel
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        // If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         // For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         //
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        // Create and display the form
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRegistroUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    /**
     * Botón que permite al administrador volver a la ventana anterior.
     */
    private javax.swing.JButton botonVolver;

    /**
     * Panel que sirve como fondo para la ventana.
     */
    private javax.swing.JPanel fondo;

    /**
     * Contenedor de desplazamiento que envuelve la tabla de movimientos.
     */
    private javax.swing.JScrollPane jScrollPane1;

    /**
     * Tabla que muestra los movimientos registrados de los usuarios.
     */
    private javax.swing.JTable tablaDeMovimientos;

    /**
     * Etiqueta que indica el título de la ventana de registro de usuarios.
     */
    private javax.swing.JLabel textRegistroUsuarios;
    // End of variables declaration//GEN-END:variables
}
