/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ve.edu.ucab.lab.Vista;

import ve.edu.ucab.lab.Controladores.ControladorCreadorDeRutasDeEjecutable;
import ve.edu.ucab.lab.Controladores.ControladorEntradaDatosAdmis;
import ve.edu.ucab.lab.Controladores.ControladorLoginAdmi;

/**
 * Ventana principal para la administración del sistema.
 * Permite la validación de los datos del administrador, la navegación a la ventana de usuario,
 * y la recuperación de la contraseña del administrador.
 *
 * @author Camila Best
 * @version 2.25.2
 */
public class VentanaAdmin extends javax.swing.JFrame {
    /**
     * La ventana de acceso del usuario.
     */
    private VentanaAccesoUsuario ventanaUsuario;
    /**
     * La cantidad de intentos restantes para el login del administrador.
     */
    private int intentos;
    /**
     * Instancia única de la clase {@code VentanaAdmin} para implementar el patrón Singleton.
     */
    private static VentanaAdmin instancia;

    private String rutaImagenes;

    private ControladorCreadorDeRutasDeEjecutable rutasDeEjecutable;

    /**
     * Obtiene la instancia única de la clase {@code VentanaAdmin}.
     * Si la instancia aún no existe, se crea una nueva.
     *
     * @return la instancia única de {@code VentanaAdmin}.
     */
    public static VentanaAdmin getInstance() {
        if (instancia == null) {
            instancia = new VentanaAdmin();
        }
        return instancia;
    }

    /**
     * Establece la ventana de acceso del usuario.
     *
     * @param ventanaUsuario La ventana de acceso del usuario.
     */
    public void setVentanaUsuario(VentanaAccesoUsuario ventanaUsuario) {
        this.ventanaUsuario = ventanaUsuario;
    }

    /**
     * Crea una nueva instancia de la ventana de acceso de usuario.
     */
    public void crearVentanaUsuario() {
        ventanaUsuario = new VentanaAccesoUsuario(); // Crea una instancia de la ventana de usuario
    }

    /**
     * Constructor que inicializa la ventana de administración.
     * Crea la ventana de usuario y establece la ubicación centrada en la pantalla.
     */
    public VentanaAdmin() {
        initComponents();
        crearVentanaUsuario(); // Crea la ventana de Usuario en el constructor
        setLocationRelativeTo(null);
        intentos = 2;
    }

    public void archivito(String rutaimg,String png){
        rutasDeEjecutable=new ControladorCreadorDeRutasDeEjecutable("",rutaimg,"",png);
        rutasDeEjecutable.rutas();
        rutaImagenes=rutasDeEjecutable.getRutaImagenes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ImagenCiudad = new javax.swing.JLabel();
        ImagenCiudad1 = new javax.swing.JLabel();
        TituloRapidoCash = new javax.swing.JLabel();
        ImagenDinero = new javax.swing.JLabel();
        TextIniciarSesion = new javax.swing.JLabel();
        TextNumeroDeTelefono = new javax.swing.JLabel();
        nombreUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        TextPin = new javax.swing.JLabel();
        contrasenaAdmin = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        BotonSiguienteOperacionesAdm = new javax.swing.JButton();
        FotoUsuario = new javax.swing.JLabel();
        BotonModoUsuario = new javax.swing.JButton();
        textoOlvidePin = new javax.swing.JLabel();
        botonRecuperarPin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RápidoCash");
        setMinimumSize(new java.awt.Dimension(838, 501));
        setPreferredSize(new java.awt.Dimension(830, 501));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(838, 501));

        archivito("src/main/java/Imagenes/CiudadPequeña.png","CiudadPequeña.png");
        ImagenCiudad.setIcon(new javax.swing.ImageIcon(rutaImagenes)); // NOI18N

        archivito("src/main/java/Imagenes/CiudadPequeña.png","CiudadPequeña.png");
        ImagenCiudad1.setIcon(new javax.swing.ImageIcon(rutaImagenes)); // NOI18N

        TituloRapidoCash.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        TituloRapidoCash.setText("RápidoCash");

        archivito("src/main/java/Imagenes/Dinero.png","Dinero.png");
        ImagenDinero.setIcon(new javax.swing.ImageIcon(rutaImagenes)); // NOI18N

        TextIniciarSesion.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        TextIniciarSesion.setText("INICIAR SESIÓN ADMINISTRADOR");

        TextNumeroDeTelefono.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        TextNumeroDeTelefono.setText("USUARIO");

        nombreUsuario.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        nombreUsuario.setBorder(null);
        nombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreUsuarioActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        TextPin.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        TextPin.setText("PIN");

        contrasenaAdmin.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        contrasenaAdmin.setBorder(null);
        contrasenaAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contrasenaAdminActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        BotonSiguienteOperacionesAdm.setBackground(new java.awt.Color(204, 204, 204));
        BotonSiguienteOperacionesAdm.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        BotonSiguienteOperacionesAdm.setText("ENTRAR");
        BotonSiguienteOperacionesAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguienteOperacionesAdmActionPerformed(evt);
            }
        });

        archivito("src/main/java/Imagenes/Usuario.png","Usuario.png");
        FotoUsuario.setIcon(new javax.swing.ImageIcon(rutaImagenes)); // NOI18N

        BotonModoUsuario.setBackground(new java.awt.Color(204, 204, 204));
        BotonModoUsuario.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        BotonModoUsuario.setText("USUARIO");
        BotonModoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModoUsuarioActionPerformed(evt);
            }
        });

        textoOlvidePin.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textoOlvidePin.setText("Olvide mi pin");

        botonRecuperarPin.setBackground(new java.awt.Color(204, 204, 204));
        botonRecuperarPin.setText("Recuperar");
        botonRecuperarPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRecuperarPinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextIniciarSesion)
                            .addComponent(TextNumeroDeTelefono)
                            .addComponent(nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextPin)
                            .addComponent(contrasenaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BotonSiguienteOperacionesAdm)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(textoOlvidePin)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botonRecuperarPin)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                                .addComponent(FotoUsuario)))
                        .addGap(12, 12, 12)
                        .addComponent(BotonModoUsuario)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TituloRapidoCash)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ImagenDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)))
                .addComponent(ImagenCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(546, Short.MAX_VALUE)
                    .addComponent(ImagenCiudad1)
                    .addGap(0, 6, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ImagenCiudad))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(TituloRapidoCash))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(ImagenDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextIniciarSesion)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TextNumeroDeTelefono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(TextPin)
                        .addGap(4, 4, 4)
                        .addComponent(contrasenaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonSiguienteOperacionesAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoOlvidePin)
                            .addComponent(botonRecuperarPin))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BotonModoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FotoUsuario))
                        .addGap(63, 63, 63))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ImagenCiudad1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Acción realizada al escribir en el campo de nombre de usuario.
     *
     * @param evt El evento generado al escribir en el campo.
     */
    private void nombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreUsuarioActionPerformed

    /**
     * Acción realizada al escribir en el campo de contraseña de administrador.
     *
     * @param evt El evento generado al escribir en el campo.
     */
    private void contrasenaAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrasenaAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contrasenaAdminActionPerformed

    /**
     * Acción realizada al presionar el botón "Siguiente" para operar como administrador.
     * Valida la entrada del administrador y, si es correcta, abre la ventana de opciones administrativas.
     *
     * @param evt El evento generado al presionar el botón.
     */
    private void botonSiguienteOperacionesAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSiguienteOperacionesAdmActionPerformed
        String claveAdmin = new String(contrasenaAdmin.getPassword());
        ControladorEntradaDatosAdmis validacionAdmi = new ControladorEntradaDatosAdmis(nombreUsuario.getText(),
                claveAdmin);
        validacionAdmi.validarEntrada();
        boolean validacion = validacionAdmi.validado();
        nombreUsuario.setText(validacionAdmi.getUserName());
        contrasenaAdmin.setText(validacionAdmi.getPin());
        if (validacion) {
            ControladorLoginAdmi logAdmi = new ControladorLoginAdmi(nombreUsuario.getText(), claveAdmin, intentos);
            logAdmi.loginAdmi();
            if (logAdmi.resultadoAdministrador()) {
                // Se crea la ventana de Opciones Administrativas para las operaciones que realiza
                System.out.println(logAdmi.getAdmi().getNombreAdministrador());
                VentanaOpcionesAdmi opcionesAdmi = new VentanaOpcionesAdmi(logAdmi.getAdmi());
                opcionesAdmi.setVisible(true);
                opcionesAdmi.setVentanaAdmin(this);
                this.setVisible(false);
                contrasenaAdmin.setText(logAdmi.getPinAdmi());
                nombreUsuario.setText(logAdmi.getNombreUsuario());
            } else {
                intentos = intentos - 1;
                contrasenaAdmin.setText(logAdmi.getPinAdmi());
                nombreUsuario.setText(logAdmi.getNombreUsuario());
            }
        }
    }//GEN-LAST:event_BotonSiguienteOperacionesAdmActionPerformed

    /**
     * Acción realizada al presionar el botón para cambiar al modo de usuario.
     * Muestra la ventana de acceso de usuario y oculta la ventana actual.
     *
     * @param evt El evento generado al presionar el botón.
     */
    private void botonModoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModoUsuarioActionPerformed
        ventanaUsuario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonModoUsuarioActionPerformed

    /**
     * Acción realizada al presionar el botón de recuperación de PIN de administrador.
     * Abre la ventana para recuperar el PIN del administrador.
     *
     * @param evt El evento generado al presionar el botón.
     */
    private void botonRecuperarPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRecuperarPinActionPerformed
        // TODO add your handling code here:
        VentanaRecuperarPinAdmin ventanaRecuperarPinAdmin = new VentanaRecuperarPinAdmin();
        ventanaRecuperarPinAdmin.setVisible(true);
        ventanaRecuperarPinAdmin.setVentanaAdmin(this);
        this.setVisible(false);
    }//GEN-LAST:event_botonRecuperarPinActionPerformed

    /**
     * Método principal para ejecutar la ventana de administración.
     *
     * @param args Los argumentos de la línea de comandos.
     */

    public static void main(String args[]) {
        // Set the Nimbus look and feel
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        // Create and display the form
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables

    /**
     * Botón que cambia la vista a modo usuario.
     */
    private javax.swing.JButton BotonModoUsuario;

    /**
     * Botón que permite proceder con las operaciones administrativas.
     */
    private javax.swing.JButton BotonSiguienteOperacionesAdm;

    /**
     * Etiqueta para mostrar la foto del usuario.
     */
    private javax.swing.JLabel FotoUsuario;

    /**
     * Imagen de la ciudad (utilizada en la interfaz).
     */
    private javax.swing.JLabel ImagenCiudad;

    /**
     * Imagen adicional de la ciudad (utilizada en la interfaz).
     */
    private javax.swing.JLabel ImagenCiudad1;

    /**
     * Imagen que representa el dinero (utilizada en la interfaz).
     */
    private javax.swing.JLabel ImagenDinero;

    /**
     * Texto que indica el inicio de sesión en la interfaz.
     */
    private javax.swing.JLabel TextIniciarSesion;

    /**
     * Texto que indica el número de teléfono.
     */
    private javax.swing.JLabel TextNumeroDeTelefono;

    /**
     * Texto que indica el campo del PIN.
     */
    private javax.swing.JLabel TextPin;

    /**
     * Título que muestra el nombre "Rápido Cash".
     */
    private javax.swing.JLabel TituloRapidoCash;

    /**
     * Botón que permite recuperar el PIN del administrador.
     */
    private javax.swing.JButton botonRecuperarPin;

    /**
     * Campo de texto para la contraseña del administrador.
     */
    private javax.swing.JPasswordField contrasenaAdmin;

    /**
     * Panel que agrupa los componentes gráficos de la interfaz.
     */
    private javax.swing.JPanel jPanel1;

    /**
     * Separador utilizado para separar los componentes gráficos.
     */
    private javax.swing.JSeparator jSeparator1;

    /**
     * Otro separador utilizado para separar los componentes gráficos.
     */
    private javax.swing.JSeparator jSeparator2;

    /**
     * Campo de texto para el nombre de usuario.
     */
    private javax.swing.JTextField nombreUsuario;

    /**
     * Etiqueta que indica el texto "Olvidé mi PIN".
     */
    private javax.swing.JLabel textoOlvidePin;

// End of variables declaration//GEN-END:variables
}