/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ve.edu.ucab.lab.Vista;

import ve.edu.ucab.lab.Controladores.ControladorCreadorDeRutasDeEjecutable;
import ve.edu.ucab.lab.Controladores.ControladorDatosNumericosCorrectos;
import ve.edu.ucab.lab.Controladores.ControladorEnviarCorreo;
import ve.edu.ucab.lab.Controladores.ControladorPinAdmiCambiado;
import ve.edu.ucab.lab.modelo.Administrador;

/**
 * Clase que representa la ventana donde se muestra la recuperación del PIN para los usuarios.
 * Esta ventana permite al administrador o al usuario confirmar el nuevo PIN recuperado y volver a la interfaz administrativa.
 *
 * @author Camila Best
 * @version 2.28.6
 */

public class VentanaPinRecuperado extends javax.swing.JFrame {
    /**
     * Ventana previa utilizada para la recuperación del PIN.
     */
     private VentanaRecuperarPinAdmin ventanaRecuperarPin;

    /**
     * Objeto que representa al administrador que está realizando la recuperación del PIN.
     */

     private Administrador administrador;

    /**
     * Controlador encargado de gestionar el envío de correos electrónicos relacionados con la recuperación del PIN.
     */

     private ControladorEnviarCorreo envioCorreo;

    /**
     * Establece la ventana previa utilizada para la recuperación del PIN.
     *
     * @param ventanaRecuperarPin Instancia de la ventana de recuperación del PIN administrativo.
     */

    public void setVentanaRecuperarPin(VentanaRecuperarPinAdmin ventanaRecuperarPin) {
        this.ventanaRecuperarPin = ventanaRecuperarPin;
    }

    /**
     * Referencia a la ventana para recuperar el PIN del administrador.
     * Permite regresar a la ventana anterior.
     */
       private VentanaRecuperarPinAdmin ventanaRecuperarPinAdmin;

    private String rutaImagenes;

    private ControladorCreadorDeRutasDeEjecutable rutasDeEjecutable;


    /**
     * Establece la ventana de recuperación del PIN del administrador para navegar de regreso.
     *
     * @param ventanaRecuperarPinAdmin La ventana de recuperación del PIN del administrador.
     */

    public void setVentanaRecuperarPinAdmin(VentanaRecuperarPinAdmin ventanaRecuperarPinAdmin) {
        this.ventanaRecuperarPinAdmin = ventanaRecuperarPinAdmin;
    }

    /**
     * Crea una nueva instancia de la clase {@code VentanaPinRecuperado}.
     * Inicializa los componentes gráficos y configura la posición centrada en la pantalla.
     */
    public VentanaPinRecuperado(Administrador administrador) {
        initComponents();
        setLocationRelativeTo(null);
        this.administrador = administrador;
        this.envioCorreo = new ControladorEnviarCorreo();
        envioCorreo.enviarCorreo(administrador.getCorreoAdministrador());
    }

    public void archivito(String rutaimg,String png){
        rutasDeEjecutable=new ControladorCreadorDeRutasDeEjecutable("",rutaimg,"",png);
        rutasDeEjecutable.rutas();
        rutaImagenes=rutasDeEjecutable.getRutaImagenes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        ImagenDinero = new javax.swing.JLabel();
        TituloRapidoCash = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        textToken = new javax.swing.JLabel();
        nuevoPin = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        textNuevoPin = new javax.swing.JLabel();
        token = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        textNuevoPin1 = new javax.swing.JLabel();
        confirmarPin = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        botonConfirmar = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RápidoCash");
        setPreferredSize(new java.awt.Dimension(830, 540));
        setResizable(false);

        fondo.setBackground(new java.awt.Color(204, 204, 255));

        archivito("src/main/java/Imagenes/Dinero.png","Dinero.png");
        ImagenDinero.setIcon(new javax.swing.ImageIcon(rutaImagenes)); // NOI18N

        TituloRapidoCash.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        TituloRapidoCash.setText("RápidoCash");

        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel1.setText("Ingrese los siguientes datos para recuperar su pin ");

        textToken.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        textToken.setText("INGRESE EL TOKEN");

        nuevoPin.setBackground(new java.awt.Color(204, 204, 255));
        nuevoPin.setBorder(null);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        textNuevoPin.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        textNuevoPin.setText("INGRESE SU NUEVO PIN");

        token.setBackground(new java.awt.Color(204, 204, 255));
        token.setBorder(null);

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        textNuevoPin1.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        textNuevoPin1.setText("CONFIRMAR EL PIN");

        confirmarPin.setBackground(new java.awt.Color(204, 204, 255));
        confirmarPin.setBorder(null);

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        botonConfirmar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonConfirmar.setText("Confirmar Cambio");
        botonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConfirmarActionPerformed(evt);
            }
        });

        botonVolver.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addComponent(TituloRapidoCash)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ImagenDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textNuevoPin)
                            .addComponent(nuevoPin, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addComponent(botonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(token, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textToken)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(confirmarPin, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textNuevoPin1))))
                        .addGap(92, 92, 92))))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(TituloRapidoCash))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(ImagenDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(textToken)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(token, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(textNuevoPin1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(confirmarPin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textNuevoPin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nuevoPin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Acción que se ejecuta al hacer clic en el botón "Confirmar".
     * Navega a la ventana principal del administrador.
     *
     * @param evt Evento de acción generado por el botón.
     */

    private void botonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfirmarActionPerformed
        ControladorDatosNumericosCorrectos tokkenCorrecto=new ControladorDatosNumericosCorrectos(token.getText(),
                "6","Tokken");
        tokkenCorrecto.confirmarDatos();
        ControladorDatosNumericosCorrectos pinCorrecto=new ControladorDatosNumericosCorrectos(nuevoPin.getText(),
                "4","Nuevo Pin");
        pinCorrecto.confirmarDatos();
        ControladorDatosNumericosCorrectos verificarPin=new ControladorDatosNumericosCorrectos(confirmarPin.getText(),
                "4","Verificar Pin");
        verificarPin.confirmarDatos();
        if (tokkenCorrecto.errorNum() && verificarPin.errorNum() && pinCorrecto.errorNum()) {
            ControladorPinAdmiCambiado nuevoPinAdmi=new ControladorPinAdmiCambiado(token.getText(),administrador,
                    nuevoPin.getText(), envioCorreo,confirmarPin.getText());
            nuevoPinAdmi.pinCambiado();
            if (nuevoPinAdmi.esCorrecto()){
                nuevoPin.setText(nuevoPinAdmi.getNuevoPin());
                token.setText(nuevoPinAdmi.getTokken());
                confirmarPin.setText(nuevoPinAdmi.getPinConfirmado());
                VentanaAdmin ventana = VentanaAdmin.getInstance();
                ventana.setVisible(true);
                this.setVisible(false);
            }
            else {
                token.setText(nuevoPinAdmi.getTokken());
                confirmarPin.setText(nuevoPinAdmi.getPinConfirmado());
                nuevoPin.setText(nuevoPinAdmi.getNuevoPin());
            }
        }
        if (!tokkenCorrecto.errorNum()){
            token.setText("");
        }
        if (!verificarPin.errorNum()){
            confirmarPin.setText("");
        }
        if (!pinCorrecto.errorNum()){
            nuevoPin.setText("");
        }


    }//GEN-LAST:event_botonConfirmarActionPerformed

    /**
     * Acción que se ejecuta al hacer clic en el botón "Volver".
     * Regresa a la ventana anterior de recuperación del PIN del administrador.
     *
     * @param evt Evento de acción generado por el botón.
     */

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        // TODO add your handling code here:
        ventanaRecuperarPin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonVolverActionPerformed

    /**
     * Método principal para ejecutar la ventana de recuperación del PIN.
     *
     * @param args Argumentos de línea de comandos.
     */

    public static void main(String args[]) {
        // Set the Nimbus look and feel
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        // If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         // For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         //
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPinRecuperado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPinRecuperado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPinRecuperado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPinRecuperado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        Administrador administrador=null;
        // Create and display the form
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPinRecuperado(administrador).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify

    /**
     * Etiqueta que muestra una imagen representativa de dinero en la interfaz.
     */
    private javax.swing.JLabel ImagenDinero;

    /**
     * Etiqueta que muestra el título "RápidoCash" en la interfaz.
     */
    private javax.swing.JLabel TituloRapidoCash;

    /**
     * Botón que permite al usuario confirmar la acción, como establecer un nuevo PIN.
     */
    private javax.swing.JButton botonConfirmar;

    /**
     * Botón que permite al usuario regresar a la ventana anterior.
     */
    private javax.swing.JButton botonVolver;

    /**
     * Campo de texto donde el usuario debe confirmar el nuevo PIN ingresado.
     */
    private javax.swing.JTextField confirmarPin;

    /**
     * Panel que contiene y organiza los componentes gráficos de la interfaz.
     */
    private javax.swing.JPanel fondo;

    /**
     * Etiqueta adicional utilizada para mostrar texto o elementos informativos.
     */
    private javax.swing.JLabel jLabel1;

    /**
     * Separador gráfico que organiza visualmente los elementos en la interfaz.
     */
    private javax.swing.JSeparator jSeparator1;

    /**
     * Otro separador gráfico para mejorar la organización visual.
     */
    private javax.swing.JSeparator jSeparator2;

    /**
     * Tercer separador gráfico para estructurar la interfaz.
     */
    private javax.swing.JSeparator jSeparator3;

    /**
     * Campo de texto donde el usuario ingresa el nuevo PIN que desea establecer.
     */
    private javax.swing.JTextField nuevoPin;

    /**
     * Etiqueta que indica al usuario que debe ingresar un nuevo PIN.
     */
    private javax.swing.JLabel textNuevoPin;

    /**
     * Etiqueta secundaria relacionada con la introducción del nuevo PIN.
     */
    private javax.swing.JLabel textNuevoPin1;

    /**
     * Etiqueta que indica al usuario que debe ingresar un token de verificación.
     */
    private javax.swing.JLabel textToken;

    /**
     * Campo de texto donde el usuario ingresa el token de verificación necesario para confirmar el proceso.
     */
    private javax.swing.JTextField token;

// End of variables declaration

}
