/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ve.edu.ucab.lab.Vista;

import ve.edu.ucab.lab.Controladores.ControladorCreadorDeRutasDeEjecutable;
import ve.edu.ucab.lab.Controladores.ControladorEntradaDatosCliente;
import ve.edu.ucab.lab.Controladores.ControladorLoginCliente;

import java.awt.event.ActionEvent;

/**
 * Ventana para el acceso de usuarios. Permite la autenticación de los clientes
 * mediante el número de teléfono y PIN, y proporciona opciones para acceder al modo de administrador.
 *
 * @author Camila Best
 * @version 2.25.2
 */

public class VentanaAccesoUsuario extends javax.swing.JFrame {
    /**
     * Número de intentos restantes para que el cliente inicie sesión.
     */
    private int intentos;

    /**
     * Instancia única de la clase VentanaAccesoUsuario.
     */
    private static VentanaAccesoUsuario instancia;

    private String rutaImagenes;

    private ControladorCreadorDeRutasDeEjecutable rutasDeEjecutable;

    /**
     * Obtiene la instancia única de la clase VentanaAccesoUsuario.
     *
     * @return Instancia de VentanaAccesoUsuario.
     */
    public static VentanaAccesoUsuario getInstance() {
        if (instancia == null) {
            instancia = new VentanaAccesoUsuario();
        }
        return instancia;
    }

    /**
     * Constructor de la clase VentanaAccesoUsuario.
     * Inicializa la ventana de acceso y establece el número de intentos restantes.
     */

    public VentanaAccesoUsuario() {
        initComponents();
        setLocationRelativeTo(null);
        intentos=2;

    }

    public void archivito(String rutaimg,String png){
        rutasDeEjecutable=new ControladorCreadorDeRutasDeEjecutable("",rutaimg,"",png);
        rutasDeEjecutable.rutas();
        rutaImagenes=rutasDeEjecutable.getRutaImagenes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextIniciarSesion = new javax.swing.JLabel();
        TextNumeroDeTelefono = new javax.swing.JLabel();
        PinUsuario = new javax.swing.JPasswordField();
        botonModoAdministrador = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        TextPin = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        fondoBlanco = new javax.swing.JPanel();
        ImagenDinero = new javax.swing.JLabel();
        FotoUsuario = new javax.swing.JLabel();
        numeroDeTelefonoUsua = new javax.swing.JTextField();
        botonSiguienteOperaciones = new javax.swing.JButton();
        TituloRapidoCash = new javax.swing.JLabel();
        ImagenCiudad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RápidoCash");
        setName("LoginUsuario"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextIniciarSesion.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        TextIniciarSesion.setText("INICIAR SESIÓN");
        getContentPane().add(TextIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        TextNumeroDeTelefono.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        TextNumeroDeTelefono.setText("NÚMERO DE TELÉFONO");
        getContentPane().add(TextNumeroDeTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        PinUsuario.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        PinUsuario.setBorder(null);
        PinUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {

            }
        });
        getContentPane().add(PinUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 333, 36));

        botonModoAdministrador.setBackground(new java.awt.Color(204, 204, 204));
        botonModoAdministrador.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        botonModoAdministrador.setText("ADMINISTRADOR");
        botonModoAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModoAdministradorActionPerformed(evt);
            }
        });
        getContentPane().add(botonModoAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, -1, 33));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 333, 10));

        TextPin.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        TextPin.setText("PIN");
        getContentPane().add(TextPin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 333, 10));

        fondoBlanco.setBackground(new java.awt.Color(255, 255, 255));

        archivito("src/main/java/Imagenes/Dinero.png","Dinero.png");
        ImagenDinero.setIcon(new javax.swing.ImageIcon(rutaImagenes)); // NOI18N

        archivito("src/main/java/Imagenes/Usuario.png","Usuario.png");
        FotoUsuario.setIcon(new javax.swing.ImageIcon(rutaImagenes)); // NOI18N

        numeroDeTelefonoUsua.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        numeroDeTelefonoUsua.setBorder(null);
        numeroDeTelefonoUsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {

            }
        });

        botonSiguienteOperaciones.setBackground(new java.awt.Color(204, 204, 204));
        botonSiguienteOperaciones.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        botonSiguienteOperaciones.setText("Entrar");
        botonSiguienteOperaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguienteOperacionesActionPerformed(evt);
            }
        });

        TituloRapidoCash.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        TituloRapidoCash.setText("RápidoCash");

        javax.swing.GroupLayout fondoBlancoLayout = new javax.swing.GroupLayout(fondoBlanco);
        fondoBlanco.setLayout(fondoBlancoLayout);
        fondoBlancoLayout.setHorizontalGroup(
            fondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoBlancoLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(fondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numeroDeTelefonoUsua, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonSiguienteOperaciones)
                    .addGroup(fondoBlancoLayout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(FotoUsuario))
                    .addGroup(fondoBlancoLayout.createSequentialGroup()
                        .addComponent(TituloRapidoCash)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ImagenDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(166, 166, 166))
        );
        fondoBlancoLayout.setVerticalGroup(
            fondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoBlancoLayout.createSequentialGroup()
                .addGroup(fondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoBlancoLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(TituloRapidoCash))
                    .addGroup(fondoBlancoLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(ImagenDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(100, 100, 100)
                .addComponent(numeroDeTelefonoUsua, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addComponent(botonSiguienteOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(FotoUsuario)
                .addGap(15, 15, 15))
        );

        getContentPane().add(fondoBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 500));

        archivito("src/main/java/Imagenes/CiudadPequeña.png","CiudadPequeña.png");
        ImagenCiudad.setIcon(new javax.swing.ImageIcon(rutaImagenes)); // NOI18N
        getContentPane().add(ImagenCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Acción para abrir la ventana del modo administrador.
     *
     * @param evt El evento generado al presionar el botón.
     */
    private void botonModoAdministradorActionPerformed(java.awt.event.ActionEvent evt) {
        VentanaAdmin ventanaAdministrador = new VentanaAdmin();
        ventanaAdministrador.setVentanaUsuario(this);
        ventanaAdministrador.setVisible(true);
        this.setVisible(false);
    }

    /**
     * Acción para validar los datos de inicio de sesión del cliente.
     * Verifica el número de teléfono y PIN ingresados y autentica al cliente.
     * Si los datos son correctos, abre la ventana de opciones para el cliente.
     *
     * @param evt El evento generado al presionar el botón.
     */
    private void botonSiguienteOperacionesActionPerformed(ActionEvent evt) {
        String claveCliente = new String(PinUsuario.getPassword());
        ControladorEntradaDatosCliente validaciones = new ControladorEntradaDatosCliente(numeroDeTelefonoUsua.getText(), claveCliente);
        validaciones.validarEntrada();
        boolean validado = validaciones.validado();
        numeroDeTelefonoUsua.setText(validaciones.getNumeroTelf());
        PinUsuario.setText(validaciones.getPin());
        if (validado) {
            ControladorLoginCliente logCliente = new ControladorLoginCliente(numeroDeTelefonoUsua.getText(), claveCliente, intentos);
            logCliente.loginCliente();
            if (logCliente.resultado()) {
                VentanaOpcionesUsua ventanaOpcionesUsua = new VentanaOpcionesUsua(logCliente.getCliente());
                ventanaOpcionesUsua.setVisible(true);
                ventanaOpcionesUsua.setVentanaAccesoUsuario(this);
                this.setVisible(false);
                numeroDeTelefonoUsua.setText(logCliente.getTelefonoCliente());
                PinUsuario.setText(logCliente.getPinCliente());
            } else {
                intentos = intentos - 1;
                numeroDeTelefonoUsua.setText(logCliente.getTelefonoCliente());
                PinUsuario.setText(logCliente.getPinCliente());
            }
        }
    }

    /**
     * Método principal para ejecutar la aplicación.
     *
     * @param args Argumentos de la línea de comandos.
     */

    public static void main(String args[]) {
         //Set the Nimbus look and feel
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAccesoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAccesoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAccesoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAccesoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        //Create and display the form
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAccesoUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    /**
     * Imagen del usuario en la ventana de acceso.
     */
    private javax.swing.JLabel FotoUsuario;

    /**
     * Imagen de la ciudad en la ventana de acceso.
     */
    private javax.swing.JLabel ImagenCiudad;

    /**
     * Imagen relacionada con dinero en la ventana de acceso.
     */
    private javax.swing.JLabel ImagenDinero;

    /**
     * Campo para ingresar el PIN del usuario.
     */
    private javax.swing.JPasswordField PinUsuario;

    /**
     * Texto que indica que es el área de inicio de sesión.
     */
    private javax.swing.JLabel TextIniciarSesion;

    /**
     * Texto que indica que se debe ingresar el número de teléfono.
     */
    private javax.swing.JLabel TextNumeroDeTelefono;

    /**
     * Texto que indica que se debe ingresar el PIN.
     */
    private javax.swing.JLabel TextPin;

    /**
     * Título de la ventana, indicando la aplicación de "RapidoCash".
     */
    private javax.swing.JLabel TituloRapidoCash;

    /**
     * Botón que permite acceder al modo administrador.
     */
    private javax.swing.JButton botonModoAdministrador;

    /**
     * Botón que permite continuar con las operaciones después de validar el inicio de sesión.
     */
    private javax.swing.JButton botonSiguienteOperaciones;

    /**
     * Panel de fondo blanco para la ventana de acceso.
     */
    private javax.swing.JPanel fondoBlanco;

    /**
     * Separador para organizar la interfaz gráfica.
     */
    private javax.swing.JSeparator jSeparator1;

    /**
     * Otro separador para organizar la interfaz gráfica.
     */
    private javax.swing.JSeparator jSeparator2;

    /**
     * Campo de texto para ingresar el número de teléfono del usuario.
     */
    private javax.swing.JTextField numeroDeTelefonoUsua;

    // End of variables declaration//GEN-END:variables

}