/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ve.edu.ucab.lab.Vista;

import ve.edu.ucab.lab.Controladores.ControladorCreadorDeRutasDeEjecutable;
import ve.edu.ucab.lab.Controladores.ControladorDepositoRetiro;
import ve.edu.ucab.lab.modelo.Cliente;

/**
 * Ventana donde el usuario puede realizar un retiro rápido de dinero mediante montos predefinidos
 * o seleccionando una cantidad personalizada.
 *
 * @author Camila Best
 * @version 2.25.2
 */

public class VentanaRetiroRapido extends javax.swing.JFrame {

    /**
     * Referencia a la ventana de opciones del usuario para navegar entre diferentes opciones del sistema.
     */
    private VentanaOpcionesUsua ventanaOpcionesUsua;

    /**
     * Cliente que está realizando el retiro, contiene los datos del cliente.
     */
    private Cliente cliente;

    /**
     * Monto a retirar, que se actualiza según la selección del usuario.
     */
    private double datMonto;

    /**
     * Número de cuenta o referencia del cliente para realizar el retiro.
     */
    private String numero;

    private String rutaImagenes;

    private ControladorCreadorDeRutasDeEjecutable rutasDeEjecutable;


    /**
     * Establece la ventana de opciones del usuario para regresar a ella después de completar una acción.
     *
     * @param ventanaOpcionesUsua La ventana de opciones del usuario a la que se puede regresar.
     */
    public void setVentanaOpcionesUsua(VentanaOpcionesUsua ventanaOpcionesUsua) {
        this.ventanaOpcionesUsua = ventanaOpcionesUsua;
    }

    /**
     * Crea una nueva instancia de la ventana de retiro rápido con la información del cliente.
     *
     * @param cliente El cliente que está realizando el retiro.
     */
    public VentanaRetiroRapido(Cliente cliente) {
        initComponents();
        setLocationRelativeTo(null);
        this.cliente = cliente;
    }

    public void archivito(String rutaimg,String png){
        rutasDeEjecutable=new ControladorCreadorDeRutasDeEjecutable("",rutaimg,"",png);
        rutasDeEjecutable.rutas();
        rutaImagenes=rutasDeEjecutable.getRutaImagenes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextEiljamontoaretirar = new javax.swing.JLabel();
        Regresar = new javax.swing.JButton();
        Monto10 = new javax.swing.JButton();
        Monto20 = new javax.swing.JButton();
        Monto100 = new javax.swing.JButton();
        Monto200 = new javax.swing.JButton();
        IngreseCantidad = new javax.swing.JButton();
        monto5 = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RápidoCash");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextEiljamontoaretirar.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        TextEiljamontoaretirar.setForeground(new java.awt.Color(255, 255, 255));
        TextEiljamontoaretirar.setText("ELIJA EL MONTO A RETIRAR");
        getContentPane().add(TextEiljamontoaretirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 51, 498, 100));

        Regresar.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        getContentPane().add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 290, 70));

        Monto10.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Monto10.setText("10 bs");
        Monto10.setToolTipText("");
        Monto10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monto10ActionPerformed(evt);
            }
        });
        getContentPane().add(Monto10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 290, 70));

        Monto20.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Monto20.setText("20 bs");
        Monto20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monto20ActionPerformed(evt);
            }
        });
        getContentPane().add(Monto20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 290, 70));

        Monto100.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Monto100.setText("100 bs");
        Monto100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monto100ActionPerformed(evt);
            }
        });
        getContentPane().add(Monto100, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 290, 70));

        Monto200.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Monto200.setText("200 bs");
        Monto200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monto200ActionPerformed(evt);
            }
        });
        getContentPane().add(Monto200, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 290, 70));

        IngreseCantidad.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        IngreseCantidad.setText("Ingrese la cantidad");
        IngreseCantidad.setToolTipText("");
        IngreseCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingreseCantidadActionPerformed(evt);
            }
        });
        getContentPane().add(IngreseCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 290, 70));

        monto5.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        monto5.setText("5 bs");
        monto5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monto5ActionPerformed(evt);
            }
        });
        getContentPane().add(monto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 290, 70));

        archivito("src/main/java/Imagenes/Fondo.png","Fondo.png");
        Fondo.setIcon(new javax.swing.ImageIcon(rutaImagenes)); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Acción que se ejecuta al hacer clic en el botón para regresar a la ventana anterior.
     *
     * @param evt el evento de acción generado al hacer clic en el botón.
     */

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        // TODO add your handling code here:
        ventanaOpcionesUsua.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RegresarActionPerformed

    /**
     * Acción que se ejecuta al hacer clic en el botón para ingresar una cantidad personalizada que desea retirar.
     *
     * @param evt el evento de acción generado al hacer clic en el botón.
     */

    private void ingreseCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreseCantidadActionPerformed
        VentanaCantidadARetirar ventanaCantidad = new VentanaCantidadARetirar(cliente);
        ventanaCantidad.setVisible(true);
        ventanaCantidad.setVentanaRetiroRapido(this);
        this.setVisible(false);
    }//GEN-LAST:event_IngreseCantidadActionPerformed

    /**
     * Acción que se ejecuta al hacer clic en el botón para retirar un monto de 5 unidades.
     *
     * @param evt el evento de acción generado al hacer clic en el botón.
     */

    private void monto5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monto5ActionPerformed
        datMonto =Double.parseDouble(monto5.getText().replaceAll("[^0-9]", "")) ;
        /**Crea la ventana que lleva a Verificar Id luego de elegir el monto**/
        ControladorDepositoRetiro retirar=new ControladorDepositoRetiro(cliente,datMonto);
        retirar.retiro();
        if (retirar.montoEfectivo()){
            VentanaVerificarId ventanaVerificarId = new VentanaVerificarId(datMonto,cliente);
            ventanaVerificarId.setVisible(true);
            ventanaVerificarId.setVentanaRetiroRapido(this);
            this.setVisible(false);
        }
    }//GEN-LAST:event_monto5ActionPerformed

    /**
     * Acción que se ejecuta al hacer clic en el botón para retirar un monto de 10 unidades.
     *
     * @param evt el evento de acción generado al hacer clic en el botón.
     */

    private void monto10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Monto10ActionPerformed
        datMonto =Double.parseDouble(Monto10.getText().replaceAll("[^0-9]", "")) ;
        ControladorDepositoRetiro retirar=new ControladorDepositoRetiro(cliente,datMonto);
        retirar.retiro();
        if (retirar.montoEfectivo()){
            VentanaVerificarId ventanaVerificarId = new VentanaVerificarId(datMonto,cliente);
            ventanaVerificarId.setVisible(true);
            ventanaVerificarId.setVentanaRetiroRapido(this);
            this.setVisible(false);
        }
    }//GEN-LAST:event_Monto10ActionPerformed

    /**
     * Acción que se ejecuta al hacer clic en el botón para retirar un monto de 20 unidades.
     *
     * @param evt el evento de acción generado al hacer clic en el botón.
     */

    private void monto20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Monto20ActionPerformed
        datMonto =Double.parseDouble(Monto20.getText().replaceAll("[^0-9]", "")) ;
        ControladorDepositoRetiro retirar=new ControladorDepositoRetiro(cliente,datMonto);
        retirar.retiro();
        if (retirar.montoEfectivo()){
            VentanaVerificarId ventanaVerificarId = new VentanaVerificarId(datMonto,cliente);
            ventanaVerificarId.setVisible(true);
            ventanaVerificarId.setVentanaRetiroRapido(this);
            this.setVisible(false);
        }
    }//GEN-LAST:event_Monto20ActionPerformed

    /**
     * Acción que se ejecuta al hacer clic en el botón para retirar un monto de 100 unidades.
     *
     * @param evt el evento de acción generado al hacer clic en el botón.
     */

    private void monto100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Monto100ActionPerformed
        datMonto =Double.parseDouble(Monto100.getText().replaceAll("[^0-9]", "")) ;
        ControladorDepositoRetiro retirar=new ControladorDepositoRetiro(cliente,datMonto);
        retirar.retiro();
        if (retirar.montoEfectivo()){
            VentanaVerificarId ventanaVerificarId = new VentanaVerificarId(datMonto,cliente);
            ventanaVerificarId.setVisible(true);
            ventanaVerificarId.setVentanaRetiroRapido(this);
            this.setVisible(false);
        }
    }//GEN-LAST:event_Monto100ActionPerformed

    /**
     * Acción que se ejecuta al hacer clic en el botón para retirar un monto de 200 unidades.
     *
     * @param evt el evento de acción generado al hacer clic en el botón.
     */

    private void monto200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Monto200ActionPerformed
        datMonto =Double.parseDouble(Monto200.getText().replaceAll("[^0-9]", "")) ;
        ControladorDepositoRetiro retirar=new ControladorDepositoRetiro(cliente,datMonto);
        retirar.retiro();
        if (retirar.montoEfectivo()){
            VentanaVerificarId ventanaVerificarId = new VentanaVerificarId(datMonto,cliente);
            ventanaVerificarId.setVisible(true);
            ventanaVerificarId.setVentanaRetiroRapido(this);
            this.setVisible(false);
        }
    }//GEN-LAST:event_Monto200ActionPerformed

    /**
     * Método principal para ejecutar la ventana de retiro rápido.
     * Se inicializa un cliente y se muestra la interfaz gráfica.
     *
     * @param args Argumentos de línea de comandos.
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRetiroRapido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRetiroRapido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRetiroRapido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRetiroRapido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        Cliente cliente=null;
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRetiroRapido(cliente).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables

    /**
     * Fondo de la ventana, representa la imagen o color de fondo de la interfaz.
     */
    private javax.swing.JLabel Fondo;

    /**
     * Botón que permite al usuario ingresar una cantidad personalizada para el retiro.
     */
    private javax.swing.JButton IngreseCantidad;

    /**
     * Botón que representa la opción de retirar 10 unidades monetarias.
     */
    private javax.swing.JButton Monto10;

    /**
     * Botón que representa la opción de retirar 100 unidades monetarias.
     */
    private javax.swing.JButton Monto100;

    /**
     * Botón que representa la opción de retirar 20 unidades monetarias.
     */
    private javax.swing.JButton Monto20;

    /**
     * Botón que representa la opción de retirar 200 unidades monetarias.
     */
    private javax.swing.JButton Monto200;

    /**
     * Botón que permite regresar a la ventana anterior del sistema.
     */
    private javax.swing.JButton Regresar;

    /**
     * Etiqueta que muestra el texto de indicación para que el usuario seleccione un monto a retirar.
     */
    private javax.swing.JLabel TextEiljamontoaretirar;

    /**
     * Botón que representa la opción de retirar 5 unidades monetarias.
     */
    private javax.swing.JButton monto5;

// End of variables declaration//GEN-END:variables

}
