/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ve.edu.ucab.lab.Vista;

import ve.edu.ucab.lab.Controladores.RegistroAdministrador;
import ve.edu.ucab.lab.modelo.Administrador;

/**
 * Ventana que muestra el registro de operaciones realizadas por los clientes en el cajero automático.
 * Esta ventana está destinada al administrador y permite visualizar todas las operaciones realizadas.
 *
 * @author Camila Best
 * @version 2.25.2
 */

public class VentanaRegistroAdministrador extends javax.swing.JFrame {

    /**
     * Instancia de la ventana de opciones del administrador. Esta variable mantiene una referencia
     * a la ventana que permite al administrador interactuar con el sistema, incluyendo la opción
     * de ver registros de operaciones.
     */

    private VentanaOpcionesAdmi ventanaOpcionesAdmi;

    /**
     * Objeto que representa al administrador actual.
     * Contiene la información del administrador que está utilizando el sistema.
     */

    private Administrador administrador;

    /**
     * Establece la ventana de opciones del administrador.
     *
     * @param ventanaOpcionesAdmi La ventana de opciones del administrador.
     */
    public void setVentanaOpcionesAdmi(VentanaOpcionesAdmi ventanaOpcionesAdmi) {
        this.ventanaOpcionesAdmi = ventanaOpcionesAdmi;
    }

    /**
     * Crea una nueva ventana para mostrar el registro de operaciones.
     */
    public VentanaRegistroAdministrador(Administrador administrador) {
        initComponents();
        setLocationRelativeTo(null); // Centra la ventana en la pantalla
        this.administrador = administrador;

        // Cargar los datos en la tabla
        RegistroAdministrador registro = new RegistroAdministrador();
        tablaDeMovimientos.setModel(registro.cargarDatos());
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        textoRegistroDeMovimientos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDeMovimientos = new javax.swing.JTable();
        botonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RápidoCash");
        setResizable(false);

        fondo.setBackground(new java.awt.Color(204, 204, 255));

        textoRegistroDeMovimientos.setFont(new java.awt.Font("Roboto Black", 0, 34)); // NOI18N
        textoRegistroDeMovimientos.setText("Registro de Movimientos de Administradores");

        tablaDeMovimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Administrador", "Tipo de Movimiento", "Persona", "Teléfono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaDeMovimientos.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tablaDeMovimientosAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tablaDeMovimientos);

        botonVolver.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoRegistroDeMovimientos)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addComponent(textoRegistroDeMovimientos)
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Acción que se ejecuta cuando se hace clic en el botón "Volver".
     * La ventana de opciones del administrador se hace visible y la ventana de registro de operaciones se oculta.
     *
     * @param evt El evento de acción.
     */

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        // TODO add your handling code here:
        ventanaOpcionesAdmi.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_botonVolverActionPerformed

    /**
     * Acción que se ejecuta cuando la tabla de movimientos se agrega al componente visual.
     *
     * @param evt El evento de adición del ancestro.
     */

    private void tablaDeMovimientosAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tablaDeMovimientosAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaDeMovimientosAncestorAdded

    /**
     * Método principal que inicializa y muestra la ventana de registro de operaciones.
     *
     * @param args Los argumentos de línea de comandos (no utilizados).
     */

    public static void main(String args[]) {
        /// Set the Nimbus look and feel
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        //If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         // For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         //
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        Administrador administrador=null;
        // Create and display the form
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRegistroAdministrador(administrador).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables

    /**
     * Botón que permite al usuario volver a la ventana anterior.
     * Este botón desencadena la acción de volver al menú o vista anterior
     * cuando es presionado.
     */
    private javax.swing.JButton botonVolver;

    /**
     * Panel que actúa como el fondo para la ventana de registro de movimientos.
     * Es utilizado como contenedor visual para otros componentes de la interfaz.
     */
    private javax.swing.JPanel fondo;

    /**
     * Contenedor de desplazamiento que envuelve la tabla de movimientos.
     * Se utiliza para permitir que los usuarios vean más filas de la tabla
     * mediante desplazamiento cuando hay muchas filas de datos.
     */
    private javax.swing.JScrollPane jScrollPane1;

    /**
     * Tabla que muestra los registros de movimientos bancarios de los usuarios.
     * Esta tabla es donde se presentan los detalles de las transacciones,
     * como el tipo de movimiento, fecha y saldo.
     */
    private javax.swing.JTable tablaDeMovimientos;

    /**
     * Etiqueta que muestra el título o encabezado de la ventana de registro de movimientos.
     * Generalmente se usa para indicar a los usuarios el propósito de la ventana.
     */
    private javax.swing.JLabel textoRegistroDeMovimientos;

    // End of variables declaration//GEN-END:variables


}
