/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ve.edu.ucab.lab.Vista;

import ve.edu.ucab.lab.Controladores.ControladorCreadorDeRutasDeEjecutable;
import ve.edu.ucab.lab.Controladores.ControladorLlenarRegistroActividarAdministrador;
import ve.edu.ucab.lab.Controladores.EliminarUsuario;
import ve.edu.ucab.lab.modelo.Administrador;
import ve.edu.ucab.lab.modelo.TransaccionesAdministradores;

import javax.swing.*;
import java.time.LocalDate;

/**
 * VentanaEliminarUsuario es la clase que representa la ventana de eliminación de usuario en la aplicación.
 * Permite al administrador buscar y eliminar usuarios del sistema.
 *
 * @author Camila Best
 * @author Daniel Agudelo
 * @version 2.8.2
 */

public class VentanaEliminarUsuario extends javax.swing.JFrame {

    /**
     * Ventana principal que contiene las opciones administrativas.
     */
    private VentanaOpcionesAdmi ventanaOpcionesAdmi;

    /**
     * Controlador encargado de manejar la eliminación de usuarios.
     */
    private EliminarUsuario eliminarUsuario;

    /**
     * Objeto que representa al administrador que realiza las acciones.
     */
    private Administrador administrador;

    /**
     * Describe el tipo de acción realizada, por ejemplo, "Eliminar Usuario".
     */
    private String movimiento;

    /**
     * Fecha en la que se realiza la acción.
     */
    private LocalDate fecha;

    private String rutaImagenes;

    private ControladorCreadorDeRutasDeEjecutable rutasDeEjecutable;


    /**
     * Establece la ventana principal de opciones del administrador.
     *
     * @param ventanaOpcionesAdmi Instancia de la ventana principal del administrador.
     */

    public void setVentanaOpcionesAdmi(VentanaOpcionesAdmi ventanaOpcionesAdmi) {
        this.ventanaOpcionesAdmi = ventanaOpcionesAdmi;
    }

    /**
     * Constructor por defecto. Inicializa la ventana y sus componentes.
     */
    public VentanaEliminarUsuario(Administrador administrador) {
        initComponents();
        setLocationRelativeTo(null);
        eliminarUsuario = new EliminarUsuario();  // Inicializamos la instancia del controlador
        this.administrador = administrador;
        System.out.println(administrador.getNombreAdministrador());
        this.fecha = LocalDate.now();
        this.movimiento = "Eliminar Usuario";

    }

    public void archivito(String rutaimg,String png){
        rutasDeEjecutable=new ControladorCreadorDeRutasDeEjecutable("",rutaimg,"",png);
        rutasDeEjecutable.rutas();
        rutaImagenes=rutasDeEjecutable.getRutaImagenes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        TituloRapidoCash = new javax.swing.JLabel();
        IconoDinero = new javax.swing.JLabel();
        textoEliminarUsuario = new javax.swing.JLabel();
        textoTelefonoUsuario = new javax.swing.JLabel();
        datoTelefonoUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        botonBuscarUsuario = new javax.swing.JButton();
        botonEliminarUsuario = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RápidoCash");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo.setBackground(new java.awt.Color(204, 204, 255));

        TituloRapidoCash.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        TituloRapidoCash.setText("RápidoCash");

        archivito("src/main/java/Imagenes/Dinero.png","Dinero.png");
        IconoDinero.setIcon(new javax.swing.ImageIcon(rutaImagenes)); // NOI18N

        textoEliminarUsuario.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        textoEliminarUsuario.setText("Eliminar Usuario");

        textoTelefonoUsuario.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        textoTelefonoUsuario.setText("TELÉFONO DEL USUARIO");

        datoTelefonoUsuario.setBackground(new java.awt.Color(204, 204, 255));
        datoTelefonoUsuario.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        datoTelefonoUsuario.setBorder(null);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jTable1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre ", "Apellido", "Cédula", "Télefono", "Correo Electrónico", "Cuenta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        botonBuscarUsuario.setBackground(new java.awt.Color(204, 204, 204));
        botonBuscarUsuario.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonBuscarUsuario.setText("Buscar");
        botonBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarUsuarioActionPerformed(evt);
            }
        });

        botonEliminarUsuario.setBackground(new java.awt.Color(204, 204, 204));
        botonEliminarUsuario.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonEliminarUsuario.setText("Eliminar");
        botonEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarUsuarioActionPerformed(evt);
            }
        });

        botonVolver.setBackground(new java.awt.Color(204, 204, 204));
        botonVolver.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(25, 642, Short.MAX_VALUE)
                .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonEliminarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TituloRapidoCash)
                            .addComponent(textoEliminarUsuario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IconoDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoTelefonoUsuario)
                            .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(datoTelefonoUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(botonBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(TituloRapidoCash)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoEliminarUsuario))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(IconoDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(textoTelefonoUsuario)
                .addGap(18, 18, 18)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(datoTelefonoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botonBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(botonEliminarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Este método se ejecuta cuando se presiona el botón "Buscar Usuario".
     * Obtiene el número de teléfono ingresado y busca el cliente en la base de datos,
     * actualizando la tabla con la información correspondiente.
     *
     * @param evt Evento de acción que se dispara al presionar el botón.
     */
    private void botonBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {
        // Obtiene el número de teléfono ingresado por el usuario
        String telefono = datoTelefonoUsuario.getText().trim();

        // Llama al método de EliminarUsuario para buscar y actualizar la tabla
        EliminarUsuario.buscarClienteYActualizarTabla(telefono, jTable1);
        TransaccionesAdministradores transaccionAdmi=new TransaccionesAdministradores(fecha,administrador.getUserAdministrador(),
                movimiento,datoTelefonoUsuario.getText(),"");
        ControladorLlenarRegistroActividarAdministrador movAdministrador=new ControladorLlenarRegistroActividarAdministrador(
                transaccionAdmi);
        movAdministrador.subirMovimientosAdmis();
    }


    /**
     * Este método se ejecuta cuando se presiona el botón "Volver".
     * Permite al administrador regresar a la ventana de opciones del administrador.
     *
     * @param evt Evento de acción que se dispara al presionar el botón "Volver".
     */
    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        // TODO add your handling code here:
        ventanaOpcionesAdmi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonVolverActionPerformed

    /**
     * Este método se ejecuta cuando se presiona el botón "Eliminar Usuario".
     * Elimina al usuario con el número de teléfono ingresado en el campo de texto.
     *
     * @param evt Evento de acción que se dispara al presionar el botón "Eliminar Usuario".
     */

    private void botonEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarUsuarioActionPerformed
        String telefono = datoTelefonoUsuario.getText().trim();

        boolean eliminado = eliminarUsuario.eliminarClientePorTelefono(telefono);

        if (eliminado) {
            JOptionPane.showMessageDialog(this, "Cliente eliminado exitosamente.");
            datoTelefonoUsuario.setText("");  // Limpiar el campo de teléfono
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo eliminar al cliente.");
        }
    }//GEN-LAST:event_botonEliminarUsuarioActionPerformed

    /**
     * Método principal que inicializa y muestra la ventana de eliminación de usuario.
     *
     * @param args Argumentos de la línea de comandos.
     */

    public static void main(String args[]) {
        // Set the Nimbus look and feel
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        // If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         // For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         //
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEliminarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEliminarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEliminarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEliminarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        Administrador administrador=null;
        // Create and display the form
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEliminarUsuario(administrador).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables

    /**
     * Icono representativo de dinero, utilizado como parte del diseño visual de la ventana.
     */
    private javax.swing.JLabel IconoDinero;

    /**
     * Título principal de la ventana, muestra el texto "RápidoCash" como encabezado.
     */
    private javax.swing.JLabel TituloRapidoCash;

    /**
     * Botón que permite buscar un usuario ingresando un número de teléfono.
     */
    private javax.swing.JButton botonBuscarUsuario;

    /**
     * Botón que permite eliminar un usuario ingresando un número de teléfono.
     */
    private javax.swing.JButton botonEliminarUsuario;

    /**
     * Botón que permite volver a la ventana de opciones administrativas.
     */
    private javax.swing.JButton botonVolver;

    /**
     * Campo de texto donde el administrador ingresa el número de teléfono del usuario a buscar o eliminar.
     */
    private javax.swing.JTextField datoTelefonoUsuario;

    /**
     * Panel principal que contiene los elementos gráficos de la ventana.
     */
    private javax.swing.JPanel fondo;

    /**
     * Componente que permite visualizar una tabla dentro de un área desplazable.
     */
    private javax.swing.JScrollPane jScrollPane1;

    /**
     * Separador gráfico que divide visualmente los componentes de la interfaz.
     */
    private javax.swing.JSeparator jSeparator1;

    /**
     * Tabla que muestra los datos del usuario encontrado o listado por el administrador.
     */
    private javax.swing.JTable jTable1;

    /**
     * Etiqueta que muestra el texto "Eliminar Usuario", indicando la funcionalidad de la ventana.
     */
    private javax.swing.JLabel textoEliminarUsuario;

    /**
     * Etiqueta que muestra el texto "Teléfono Usuario", indicando el propósito del campo de texto asociado.
     */
    private javax.swing.JLabel textoTelefonoUsuario;

// End of variables declaration//GEN-END:variables

}
